### ISSUE TITLE
used_formats may be obsolete feature

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#100]
im not sure if we need to leave this in for backward compatibility, or how many people are using this. but it seems like this defaults to only displaying used now. which is really how it should work. I tried doing `used_formats="0"` and it did not work. I would expect that that would display every format in the server. if we decide to keep for backward compatibility sake, I would suggest just removing this feature from the docs and keep it undocumented maybe. as there doesnt seem to be a `used_formats="0"`. this was really a patch that I implemented from the move to sezf and how formats where being pulled previously.

**Comment by radius314** [comment]
yeah, it should be removed.

**Comment by radius314** [comment]
rolled into master
