### ISSUE TITLE
include_weekday_button=0 should default to city view

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#101]
ref #45 

if using `include_weekday_button="0"` it should default to city view. as weekday is default it defaults there and still displays weekday button.

**Comment by radius314** [comment]
I'm not sure this is a regression @pjaudiomv , it's no different that the situation we were in before with #45 .  Correct me if I'm wrong.

**Comment by radius314** [comment]
The reason this happens is because `view_by` takes precedence over buttons.  We would have to change the logic of how it operates to have the buttons override the `view_by` feature.  Not sure it makes sense to do this.

https://github.com/bmlt-enabled/crouton/blob/master/crouton.php#L298
https://github.com/bmlt-enabled/crouton/blob/master/crouton.php#L337

**Comment by radius314** [comment]
All the logic needs to be moved to javascript anyway as part of #98 .  I would rather leave things status quo, since there is a workaround by setting `view_by='city'`

**Comment by pjaudiomv** [comment]
this all makes sens, maybe in instructions under Exclude Weekday Button we just say yo if you set this to 0 you should change view_by to city.

**Comment by radius314** [comment]
done

**Comment by radius314** [comment]
I am working on a new feature that would allow a user to specify other "filter buttons" to use.  In this scenario, it wouldn't make sense to assume that if the weekday button is hidden that the default view is the city button.

**Comment by radius314** [comment]
This feature won't make sense in Crouton 2.3.0 since there is no guarantee that a button will be visible.

**Comment by radius314** [comment]
I have an idea of how to implement the default view.  If no view is selected, it would use the first one in the button_filter.  This requires that the weekday button be refactored into this construct (it's not going to be in 3.3.0)

**Comment by pjaudiomv** [comment]
I feel like we can close this.
