### ISSUE TITLE
Formats tab do not display. It shows the comment :"No result found". 

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#105]
After updating the plugin to version to 2.6.0, I have checked all tabs and Format wasn't displayed.
That is strange, because the new pre-released (tested) version was all Okay.

**Comment by Klodd65** [comment]
That is weird because it is worked on https://na-outaouais.org/reunions/ but not to this link https://naquebec.org/trouver-une-reunion/

**Comment by radius314** [comment]
Same BMLT root server?

**Comment by radius314** [comment]
Looks like different root servers. "http://fr.csrqna.membres.naquebec.org/main_server/" is running a very old version.

**Comment by radius314** [comment]
crouton 2.6.0 requires root server version 2.10.3 or higher.

**Comment by Klodd65** [comment]
solved
