### ISSUE TITLE
Crouton not displaying meetings on ie11

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#106]
Ref #72

**Comment by pjaudiomv** [comment]
looks like it was the punycode that killed it this is form the latest published version 2.6.0? js console from ie11
![jsie11_crouton](https://user-images.githubusercontent.com/34245618/57575781-4dd31c80-741f-11e9-8693-e1f173d53588.PNG)

**Comment by pjaudiomv** [comment]
looks like this version would support ie11 as doesn't use es6
https://github.com/bestiejs/punycode.js/releases/tag/v1.4.1

read that in readme here https://www.npmjs.com/package/punycode

**Comment by radius314** [comment]
ok will try with 1.4.1, downloading ie 11 vm now

**Comment by radius314** [comment]
punycode support added for ES5 is now in master.

**Comment by pjaudiomv** [comment]
cool I just tested with ie11 and is working now

**Comment by radius314** [comment]
still working on beta1?

**Comment by pjaudiomv** [comment]
Yep still working

**Comment by radius314** [comment]
resolved in 3.0.0
