### ISSUE TITLE
crouton 3 / areas dd

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#108]
The areas dropdown is displaying and populating, however two things.

 - [x] 1. Its not sorting
 - [x] 2. When clicking on an area its not rendering just meetings in that area. no changes happen with meetings that are displayed, to either remove or add meetings that are or are not in that service body.
no js errors or warnings displaying. 

I tried this with both wordpress and croutonjs

**Comment by radius314** [comment]
other fix is in master

**Comment by pjaudiomv** [comment]
cool I tested this with both wp crouton and croutonjs and working great. thanks.
