### ISSUE TITLE
crouton3 css changes

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#111]
the changing of the column width percentages kind of screwed the pooch with the times. I tried a few different wordpress themes the twenty whatevers. whats happening is if the hour contains a double digit the 2nd letter ("M") of meridiem moves to next line. this could be fixed by readjusting the percentages by only a couple. 1percent fixed it on my tests. I can see making column2 bigger, but don't see the need for making column 3 bigger.

**Comment by radius314** [comment]
do you have an example somewhere?

**Comment by pjaudiomv** [comment]
this is an example https://arkansas.charlestonna.org/meetings-tabbed-ui/ the issue is depending on layout weather its full page or with sidebar it gets rendered differently. my only thing is before it was fine, now its not. to fix this I would have to add custom css. which I would still consider a breaking change.

**Comment by pjaudiomv** [comment]
its petty but wondering why the change in column width percentages were necessary.

**Comment by radius314** [comment]
I think I wanted to remove space in the 3rd column, I sent a change to master which should fix this.

**Comment by radius314** [comment]
had a chance to re-test?

**Comment by pjaudiomv** [comment]
Yes I did and is fine but I would like to make a case to take 5% from column1 and move to column2 :)

**Comment by radius314** [comment]
sure send a PR
