### ISSUE TITLE
kmeleon browser support

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/crouton#114]
it was reported that crouton was not working on this browser

**Comment by pjaudiomv** [comment]
I just tested crouton 3.0.0-beta1 with the latest stable kmeleon 75.1 (released 3.5yrs ago) and works fine. I also tested with crouton 2.6.0 and it did not work.

**Comment by pjaudiomv** [comment]
it didnt like punycode, so must not have es6 support or limited. either way crouton 3 runs fine on it.

**Comment by radius314** [comment]
Want to update FB post?

**Comment by pjaudiomv** [comment]
cool just did

**Comment by radius314** [comment]
verified
