### ISSUE TITLE
[meeting_count] is overriding settings for [bmlt_tabs]

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#118]

**Comment by radius314** [comment]
what kind of settings do you want to override?

**Comment by pjaudiomv** [comment]
when i use [meeting_count service_body="8"]
and [bmlt_tabs service_body="8" header="0" has_tabs="0"] it is overiding the header and has_tabs settings using https://www.nerna.org/main_server. however this is happening without the service body parameter as well here
https://arkansas.charlestonna.org/crouton/
[meeting_count]
[bmlt_tabs header="0" has_tabs="0"]

**Comment by radius314** [comment]
can you try to use 

`[init_crouton service_body="8" header="0" has_tabs="0"]`

`[meeting_count]`

`[bmlt_tabs]`

**Comment by radius314** [comment]
you could also do 

`[meeting_count service_body="8" header="0" has_tabs="0"]`

`[bmlt_tabs]`

**Comment by radius314** [comment]
The old way of doing things was janky (riddled with bugs), maybe this needs to be documented a little clearer.  But once the crouton is initialized that's what the settings are for it.  It's not going to initialize more than one crouton per page.

**Comment by pjaudiomv** [comment]
cool all of those things fixed it, ya agree could probably use clearer documentation as this is a breaking change for backward compatibility.

**Comment by radius314** [comment]
I am doubtful that people are using the shortcodes this way.  So the blast radius is proabably rather small.

**Comment by pjaudiomv** [comment]
its a pretty common thing to display the amount of meetings on the same page. however maybe not service body specific idk to me this isn't intuitive.

[meeting_count service_body="8" header="0" has_tabs="0"]
[bmlt_tabs]

and this is

[meeting_count]
[bmlt_tabs service_body="8" header="0" has_tabs="0"]

however does make sense now that i know how this new version operates.

**Comment by radius314** [comment]
It is pretty common, but it’s probably not as common to hide tabs and the header (or change other tabbed elements), and also show the meeting_count.

There is a fix for this, but it requires another set of refactoring.

**Comment by pjaudiomv** [comment]
ah true true

**Comment by radius314** [comment]
I think I might have a quick fix for this.

**Comment by radius314** [comment]
I pushed a fix for this, will be in build 169.

**Comment by pjaudiomv** [comment]
just tested that fixed it, thanks.

**Comment by radius314** [comment]
released in 3.0.3
