### ISSUE TITLE
3.0.3 crouton not loading texas

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#121]
for crouton 3.0.3 and following settings, crouton is not loading.

`[bmlt_tabs show_map="1" max_zoom_level="7"]`
`https://texasoklahomana.org/main_server/ Louisiana Region (1054)`

I have tested this and am getting this in console

Loading failed for the <script> with source “https://texasoklahomana.org/main_server/client_interface/jsonp/?switcher=GetSearchResults&data_field_key=location_postal_code_1,duration_time,start_time,weekday_tinyint,service_body_bigint,longitude,latitude,location_province,location_municipality,location_street,location_info,location_text,formats,format_shared_id_list,comments,meeting_name,location_sub_province,worldid_mixed,root_server_uri&services[]=0&recursive=1&sort_key=time&callback=jQuery1124031118579482544806_1559595565535&_=1559595565536”. tex:1:1

​it seems to be a problem with recursive service body maybe with their service body structure, the query has '&services[]=0' however it should be `&services[]=1054`

**Comment by pjaudiomv** [comment]
or wordpress plugin not properly passing the config idk

**Comment by radius314** [comment]
Is recursive enabled?

**Comment by californiasteve** [comment]
No

⁣Get BlueMail for Android ​

**Comment by radius314** [comment]
Are there meetings specified at the regional level?

**Comment by radius314** [comment]
Nm, it automatically turns it on if the parent is 0.  Legacy code.

**Comment by californiasteve** [comment]
I unchecked the "extra meetings included" checkbox, saved it, and the check box was still checked.

**Comment by californiasteve** [comment]
![image](https://user-images.githubusercontent.com/31661648/58840893-0f4f0d00-862d-11e9-9db9-31374ec480c2.png)

**Comment by radius314** [comment]
I know what the issue is.  Fix is coming.

**Comment by radius314** [comment]
Please test out the fix https://archives.bmlt.app/crouton/crouton-build173-975c216b4fa5ca6388fd677dd588f6810bb2598b.zip

**Comment by californiasteve** [comment]
Works like a charm, thanks.
