### ISSUE TITLE
Update list of meetings based off what's visible in map.

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#123]
Can we use tomato to display map so when scrolling it would show all published BMLT meetings?

**Comment by radius314** [comment]
I would imagine that a better change would be to actually update the tabs realtime with what's in the viewport window.  Alone it doesn't really make sense to do this.

**Comment by californiasteve** [comment]
That makes more sense.

**Comment by radius314** [comment]
With the implementation of #126, this doesn't make too much sense.
