### ISSUE TITLE
Crouton don't load translation anymore

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#124]
Here's my shortcode : [bmlt_tabs time_format="HH:mm" bmlt_tabs language="fr-CA" bmlt_tabs show_map="1" bmlt_tabs show_distance="1" distance_units="km" bmlt_tabs has_areas='1'  has_sub_province='1' has_zip_codes='0' ]

**Comment by californiasteve** [comment]
I'm getting the translation in the meeting results but not in the header tabs.
![image](https://user-images.githubusercontent.com/31661648/59132499-fa2ef280-893a-11e9-9c4e-1343153191bb.png)

**Comment by radius314** [comment]
You should not be repeating `bmlt_tabs` over and over.  Just one time.

**Comment by radius314** [comment]
fixed in 3.0.5, please let me know if it works for you.

**Comment by pjaudiomv** [comment]
I tested as well and is loading fine here https://arkansas.charlestonna.org/lang/

**Comment by californiasteve** [comment]
Looks good, translating all tabs and results.

**Comment by Klodd65** [comment]
1. is it ok if I clone the plugin into my cPanel that shows you a live result on https://naquebec.org?
(Now I cannot see anything)
 2. By updating updates, nothing has change but it displays the UI.
