### ISSUE TITLE
browser asking for location regardless of setting.

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#129]
using this latest build (https://archives.bmlt.app/crouton/crouton-build184-89b3d29fb105703fee9d2d2057fe63e91e78e538.zip)[https://archives.bmlt.app/crouton/crouton-build184-89b3d29fb105703fee9d2d2057fe63e91e78e538.zip]

browser is now always asking me to share my location regardless of whether `show_distance` or `distance_search` is being used.

**Comment by radius314** [comment]
able to repro

**Comment by radius314** [comment]
This has been fixed in build 185.

**Comment by ChrisMarshallNY** [comment]
Cool. This has been an issue since Jack first wrote it. If you had a shortcode that summed up the meetings, it would ask for your location. Since it was usually on the same page as the main map search, it was often missed.

**Comment by radius314** [comment]
@pjaudiomv able to validate this fix?

**Comment by pjaudiomv** [comment]
I have not yet, I will when I get home.

**Comment by radius314** [comment]
K

**Comment by pjaudiomv** [comment]
yes this works fine now

**Comment by radius314** [comment]
Cool thanks
