### ISSUE TITLE
Distance to meeting

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/crouton#130]
Distance to meeting has stopped working for me.  Not sure how long ago.  I checked it on my phone and desktop and its not working either place, nor is it working on my work computer. just checking those places also in case there was something wrong with the location on my device. 

Here's my code (which i haven't changed in months): [bmlt_tabs has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]

**Comment by radius314** [comment]
This is definitely a bug and I can reproduce it.

**Comment by radius314** [comment]
I was incorrect.  I cannot reproduce this error locally.

What are the short codes for [meeting_count] and [group_count]?

**Comment by lucy12187** [comment]
<strong>The Volunteer Region now has [group_count] groups with
[meeting_count] meetings per week.
</strong><em>Miles = your distance to the meeting if geolocation permission
is enabled.</em>

[bmlt_tabs has_areas='1'
show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]

**Comment by lucy12187** [comment]
I've got lots of this error in the error log.  I'll contact bluehost and ask them about this.  not sure if it could have anything to do with the distance to meetings not working.

[10-May-2019 12:00:29 America/Chicago] PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1657 but version 1650 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
[27-Jun-2019 07:30:07 America/Chicago] PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1657 but version 1650 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

**Comment by lucy12187** [comment]
There are also some twilio and yap errors in there.

**Comment by radius314** [comment]
The error is unrelated to crouton.

**Comment by radius314** [comment]
Ok, I know what the issue is.

**Comment by radius314** [comment]
Can you modify the shortcode to have all the parameters in the [meeting_count] one?  The way this works (and should've), is that you put the parameters first and then all the rest inherit from the last use.

**Comment by lucy12187** [comment]
like this?

*The Volunteer Region now has [group_count] groups with [meeting_count
bmlt_tabs has_areas='1'
show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"
] meetings per week.*

**Comment by lucy12187** [comment]
its working like this:  [bmlt_tabs has_areas='1' show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]

The Volunteer Region now has [group_count] groups with [meeting_count]
meetings per week.
Miles = your distance to the meeting if geolocation permission is enabled.

but i'd rather not have the number of groups and meetings at the very
bottom.

is there another way to do it?

**Comment by californiasteve** [comment]
Try The Volunteer Region now has [bmlt_tabs group_count] groups with [bmlt_tabs meeting_count] meetings per week.

**Comment by lucy12187** [comment]
That didn't work.  The only combination i can get to show both is if i
place the group and meeting count BELOW the bmlt tabs short code.
weird, huh?

[bmlt_tabs has_areas='1' show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"
]

The Volunteer Region now has [group_count ] groups with [meeting_count]
meetings per week.
Miles = your distance to the meeting if geolocation permission is enabled.

**Comment by lucy12187** [comment]
I can't get any of these links to work...
i was going to see one of them explained how to do it now... I'm assuming
this is a new way since it says NEW besides URL parameters

Meetings for One Area.

https://nameetinglist.org/bmlt-tabs/?root_server
=https://naflorida.org/bmlt_server&service_body=2&this_title
=Greater%20Orlando%20Area%20Meetings&meeting_count=1&group_count=1

Meetings for Two (or more) Areas.

https://nameetinglist.org/bmlt-tabs/?root_server
=https://naflorida.org/bmlt_server&service_body=2,18&this_title
=Greater%20Orlando%20Area%20and%20Central%20Florda%20Area%20Meetings&
meeting_count=1&group_count=1
<https://nameetinglist.org/bmlt-tabs/?root_server=https://naflorida.org/bmlt_server&service_body=2,18&this_title=Greater%20Orlando%20Area%20and%20Central%20Florda%20Area&meeting_count=1&group_count=1>

Meetings for One Region.

https://nameetinglist.org/bmlt-tabs/?root_server
=https://naflorida.org/bmlt_server&service_body_parent=1&this_title
=Florida%20Region%20Meetings&meeting_count=1&group_count=1

*Title, meeting and group count have unique CSS classes that can be used
for custom styling.*

**Comment by californiasteve** [comment]
Try this
The Volunteer Region now has[bmlt_tabs] [group_count ] groups with [meeting_count] meetings per week.

**Comment by lucy12187** [comment]
That doesn't show the group or meeting count or the miles...

**Comment by lucy12187** [comment]
i just noticed that namwt.org which has the same wordpress theme as i do,
and same shortcodes on their meeting page... shows the meeting and group
count and the miles using chrome, but using edge it doesn't show the miles,
and location is on.  on the natennessee site, with the group/meeting
shortcode at the bottom, it shows the miles.

i give up for now. i'm just glad i got it to work when i add the group
count and meeting count to the bottom.  I'll just to change all the area
pages i have on our regional page, and also change namwt's page.

If y'all figure it out, let me know! :)
lucy

**Comment by radius314** [comment]
None of these are correct.

**Comment by radius314** [comment]
I thought this was related to the area pages.  I'm not sure I understand what's happening anymore.

You always need to include the settings you wish to override in the first shortcode on the page.

What this means is, if you are using meeting count do the following

[meeting_count some_parameter="1"]

[group_count]

[bmlt_tabs]

You cannot combine shortcodes together, ever.

**Comment by lucy12187** [comment]
i thought that was what you were asking me to do in the beginning was
combine my bmlt tab parameters in with the meeting count short code.
this was the first page I noticed this on:
https://natennessee.org/meetings/

My current settings work: (although i would rather not have to put the
meeting/group count at the end.
[bmlt_tabs has_areas='1' show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]
The Volunteer Region now has [group_count] groups with [meeting_count]
meetings per week.

When i had the line with the group count and meeting count BEFORE the
bmlt_tabs line, the miles didn't show up.  although it worked fine when i
first set this up some months back.
I discovered with trying different things, when I move the group count and
meeting count to after the bmlt_tabs it works.

I have a meeting page for each area
See chattanooga: https://natennessee.org/chattanooga/  - i moved the
meeting/group count to after the bmlt_tabs - and the meeting/group count
and miles show up on the page.

See Greater Nashville: https://natennessee.org/greater-nashville/  the
meeting/group count shortcodes are before the bmlt_tabs (this used to work
but no longer shows the miles.

Then I went to look at the namwt.org meeting page just to see if it was
working correctly and it wasnt either... til i moved the meeting/group
count to the end.

**Comment by radius314** [comment]
You can have the counts first as long as you add all the Parameters as part of that first shortcode.

**Comment by lucy12187** [comment]
like this [group-count has_areas='1' show_distance="1"
service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]

**Comment by radius314** [comment]
Correct

**Comment by lucy12187** [comment]
like this the meetings don't show up at all

The Volunteer Region now has [group_count has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"] groups with [meeting_count] meetings per week.

**Comment by radius314** [comment]
You will still need to include [bmlt_tabs] to render the table.

**Comment by lucy12187** [comment]
thank you! This works! 

The Volunteer Region now has [group_count has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"] groups with [meeting_count] meetings per week. [bmlt_tabs]

**Comment by lucy12187** [comment]
I can't get that same format to work on the namwt.org/meetings page.  but I'm tired and will look at it again tomorrow.

**Comment by radius314** [comment]
Looks good to me https://namwt.org/meetings ... what are you seeing?

**Comment by lucy12187** [comment]
its working now.  Last time I looked last night it wasn't. 
maybe i needed to refresh again or something, although i'm pretty sure i did.
Thanks for checking.  and for your help through all this. i learned something about the short codes i didn't know.

**Comment by radius314** [comment]
No problem.

**Comment by lucy12187** [comment]
I just updated crouton and the miles to meetings isn't showing up again.

**Comment by lucy12187** [comment]
I put it back like I had it before I changed it a couple weeks ago, and its working ok...

This is what I changed it to a couple weeks ago: The Volunteer Region now has [group_count has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"] groups with [meeting_count] meetings per week. [bmlt_tabs]

This was my original way, and when I changed it back just, it shows correctly. 
The Volunteer Region now has [group_count] groups with [meeting_count] meetings per week. [bmlt_tabs has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]
