### ISSUE TITLE
Meeting info not in Chronological order

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/crouton#132]
Please see image for details on what's happening:

![Screenshot_20190703-173132](https://user-images.githubusercontent.com/50605252/60759452-84618980-9fc1-11e9-9bfe-eb87f398ae20.png)

**Comment by pjaudiomv** [comment]
What's the short code your using and link to website it's on

**Comment by EddieW1** [comment]
Here is the short code that is being used by SGV:

[bmlt_tabs]

others are using the same short code but with their Area number.

Example below is from SFV

[bmlt_tabs service_body="1061"]

Same results

Eddie

**Comment by radius314** [comment]
Found the issue working on a patch now.

**Comment by EddieW1** [comment]
Thanks Danny.

Will apply the patch as soon as you release it.

ILS
Eddie

**Comment by radius314** [comment]
Will be in crouton 3.2.0
