### ISSUE TITLE
When I updated crouton, same miles to meetings issue.  put it back like it was to begin with (before last time) and it works.

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/crouton#134]
I put it back like I had it before I changed it a couple weeks ago, and its working ok...

This is what I changed it to a couple weeks ago: The Volunteer Region now has [group_count has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"] groups with [meeting_count] meetings per week. [bmlt_tabs]

This was my original way, and when I changed it back just now, it shows correctly. 
The Volunteer Region now has [group_count] groups with [meeting_count] meetings per week. [bmlt_tabs has_areas='1' show_distance="1" service_body_parent="1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059"]

_Originally posted by @lucy12187 in https://github.com/bmlt-enabled/crouton/issues/130#issuecomment-508973138_

**Comment by radius314** [comment]
What's the issue?

**Comment by lucy12187** [comment]
Well its not an issue if you consider its working...
When it wasn't working before this last crouton update, I changed it like you suggested to and it worked.
After this most recent update, I had to put it back like it was before.

It just seems like there is some problem/bug and that I shouldn't have to keep switching the short codes back and forth.

**Comment by radius314** [comment]
closing this for now

**Comment by lucy12187** [comment]
ok
