### ISSUE TITLE
Add language to url parameters for multiple instances

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#137]
Enhancement, add the capability to use the "language=it-IT" to the url for multiple instances of crouton.

**Comment by radius314** [comment]
testable in https://archives.bmlt.app/crouton/crouton-build211-589780ec684deefad34477b25386729282735a0a.zip

**Comment by californiasteve** [comment]
Works as expected.

**Comment by radius314** [comment]
will be in crouton 3.2.5
