### ISSUE TITLE
Add to url parameters same options available in to the shortcodes

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#141]
I have a website that I need to display virtual meetings in the timezone the user's PC is in. I also need to customize the tabs that are displayed. I don't need cities, states, zip

**Comment by californiasteve** [comment]
Will the shortcode parameters work when added to the page and using the url option?

**Comment by radius314** [comment]
URL parameters should override shortcodes always, however the way it's implemented not all parameters are overridable via querystring.  This is a feature that needs to be added in a future release.

**Comment by californiasteve** [comment]
I think we can close this then.

**Comment by radius314** [comment]
going to implement this anyway

**Comment by californiasteve** [comment]
Ok

**Comment by radius314** [comment]
in master and will be in 3.3.0
