### ISSUE TITLE
Add ability to change ordering of days of week to european format

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#143]
Italy would like to be able to have the days of the week ordered in their format of Monday through Sunday on tabs

**Comment by radius314** [comment]
first half of changes are in master now.  this will work for the tabs only.  the next set of changes are for the city and filtered views

**Comment by radius314** [comment]
2nd half of changes are in master now, there is one other change that needs to be made.

**Comment by radius314** [comment]
@californiasteve how is this working for you in the beta?

**Comment by californiasteve** [comment]
Works as expected. 
![image](https://user-images.githubusercontent.com/31661648/63356259-184aa300-c32d-11e9-9580-6c658341353b.png)
