### ISSUE TITLE
Google maps link on the Map button doesn't have any marker

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/crouton#145]
The link from the Map button is like this:

https://maps.google.com/maps?q=51.89422183,-8.4691152

That link opens a page with a map, but the map doesn't drop any marker at the address. I think  maybe google have changed this behaviour recently..  

This is a link format that will include a marker on the opened page:

https://maps.google.com/maps?daddr=51.89422183,-8.4691152

I'll open a pull request to update to the new format I think it would be better to have the marker on the map that is opened by the Map button

**Comment by radius314** [comment]
Per our discussion, this might be a bug in Chrome on Mac.

**Comment by paulnagle** [comment]
You might still want to merge https://github.com/bmlt-enabled/crouton/pull/146 

According to Google, the maps URLs are being formatted incorrectly. If you think its not worth it, you can just close the PR
