### ISSUE TITLE
city view sort not working properly on wordpress

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#147]
when selecting city view on crouton 3.3.0 the meetings aren't sorted by city, then, day, then start_time. I have yet to figure out how its being sorted but the days and city names are all over the place. this is an example shortcode `[bmlt_tabs root_server="https://www.nerna.org/main_server/" service_body="3"]` however it doesnt work with standared [bmlt_tabs] shortcode as well

https://nerna.org/meetings-by-area/cape-cod-area-meetings/

this worked fine in last version

**Comment by radius314** [comment]
It looks like its not considering AM + PM.

**Comment by radius314** [comment]
Actually it looks like the cities are not being sorted correctly.  Everything else looks fine to me.

**Comment by pjaudiomv** [comment]
weird the days def were messed up too but now they aren't, must be like my old car where it fixes itself.

**Comment by pjaudiomv** [comment]
yea just cities, havent been able to reproduce the days not being right again.

**Comment by radius314** [comment]
Fix pushed to master.

**Comment by pjaudiomv** [comment]
great just tested, works fine.

**Comment by radius314** [comment]
ok releasing
