### ISSUE TITLE
Start Day not working on page with init_crouton

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#150]
Day of week isn't moving to Monday using this shortcode.
https://naitaliadev.com
[init_crouton language="it-IT" show_distance="1" distance_units="km" has_states='1' show_map="1" time_format="HH:mm" include_city_button="0" has_sub_province='1' has_locations='0' int_start_day_id="2"]
Ci sono [group_count] gruppi per un totale di [meeting_count] riunioni.
[bmlt_tabs]

**Comment by radius314** [comment]
Can you double check that you are using double quotes for every parameter.
It looks like you are using a single quote.

**Comment by californiasteve** [comment]
It was a mixture of both. I have changed them all to double quotes and still have the same problem.

**Comment by radius314** [comment]
Can you post the url for the page having the issue?

**Comment by californiasteve** [comment]
htttps://naitaliadev.com

**Comment by californiasteve** [comment]
https://naitaliadev.com/

**Comment by pjaudiomv** [comment]
I was able to repro as well it works doing this `[bmlt_tabs root_server="https://na-italia.info/main_server" service_body_parent="1" language="it-IT" show_distance="1" distance_units="km" has_states="1" show_map="1" time_format="HH:mm" include_city_button="0" has_sub_province="1" has_locations="0" int_start_day_id="2"]` but not using `[init_crouton root_server="https://na-italia.info/main_server" service_body_parent="1" language="it-IT" show_distance="1" distance_units="km" has_states="1" show_map="1" time_format="HH:mm" include_city_button="0" has_sub_province="1" has_locations="0" int_start_day_id="2"]` then `[bmlt_tabs]`

**Comment by californiasteve** [comment]
I used your example from above and the day of week start is still Sunday.
https://naitaliadev.com/

**Comment by radius314** [comment]
It looks like every resource is loading twice.

**Comment by californiasteve** [comment]
Just verified that code is not duplicated on the page. I also see that the time format is also not working.

**Comment by radius314** [comment]
Something on the page is causing things to get loaded twice.  Not sure what plugin you are using that might be causing this.  I am unable to reproduce this issue on another Wordpress server.

**Comment by californiasteve** [comment]
I wonder if this linked to the problem I was having with the admin accordion section #151 ?

**Comment by californiasteve** [comment]
I removed the [bmlt_tabs] from the bottom of Patrick's example and moved the meeting_count and group_count to before the [bmlt_tab], now it's working as expected.
