### ISSUE TITLE
CSS not applying to admin section

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#151]
None of the color and the arrow icon for the accordion is being hidden by the text.
![image](https://user-images.githubusercontent.com/31661648/64490702-6b758e80-d225-11e9-8162-f781acc80358.png)

**Comment by pjaudiomv** [comment]
are you seeing any errors or 404s in browser dev tools

**Comment by pjaudiomv** [comment]
you may have some conflicts with theme or plugin maybe, does bread work fine?

**Comment by californiasteve** [comment]
I'm looking at css right now. Looks like the jquery is overriding it. Bread works fine.

**Comment by radius314** [comment]
Does this happen on all instances of Wordpress or just a specific instance?

**Comment by californiasteve** [comment]
It's specific to this website. It's probably a plugin since it was working earlier.

**Comment by radius314** [comment]
We would be hard pressed to fix this without any additional information, logs or error data.

**Comment by californiasteve** [comment]
I'll close it.

**Comment by californiasteve** [comment]
Conflict with plugin jquery.

**Comment by radius314** [comment]
How do you know it's a jQuery conflict?
