### ISSUE TITLE
fomat dropdown displaying wrong meetings

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#152]
issue was brought up on Facebook, when selecting format code `men` from the drop-down menu meetings with `women` format show up as well.

**Comment by radius314** [comment]
crouton does not discriminate

**Comment by pjaudiomv** [comment]
um when selecting women, men's meetings don't show up :(

**Comment by radius314** [comment]
Crouton secretly feels women are superior.

**Comment by pjaudiomv** [comment]
damn Crouton is probably right, I know Becky is far superior than me.

**Comment by radius314** [comment]
url to problem crouton?

**Comment by radius314** [comment]
found it https://nzna.org/meetings-list

**Comment by radius314** [comment]
Able to repro locally.

**Comment by radius314** [comment]
This appears to be as a result of this change https://github.com/bmlt-enabled/crouton/issues/92 (https://github.com/bmlt-enabled/crouton/commit/ee5fd48e531283296c5f2e533d61172fc9244ddc)

**Comment by radius314** [comment]
actually that is not true, this may have always been a bug.

**Comment by radius314** [comment]
Ok I know what the issue is.  It has to do with how the formats are referenced and how the filter works.  The formats are stored as a complete string, and I was doing partial matching on the filters.

**Comment by radius314** [comment]
sample of how the attributes are used.
![Screen Shot 2019-09-20 at 8 46 43 PM](https://user-images.githubusercontent.com/1850811/65365495-caed7a00-dbe7-11e9-95d4-f44688ba002b.png)

**Comment by radius314** [comment]
fix coming

**Comment by radius314** [comment]
delivered in 3.3.3
