### ISSUE TITLE
Feature Request: custom add fields to the default crouton display

### ISSUE THREAD

**Issue by rogersearle** [bmlt-enabled/crouton#153]
to be able to custom add fields to the default crouton display - specifically one that can represent an second "address" line for showing a city's"suburb"

**Comment by radius314** [comment]
This will be released in crouton 3.4.0.  You should be able to install this version to test it out to make sure it meets your needs.  The way this gets configured is through the use of a new feature called "Meeting Data Templates".  When you go into the admin screen you will see a new field and some pre-populated HTML templating.  

You should be able to add the fields that you need and format them accordingly.  

A list of fields is available on quick link.  I believe the one you will want to include is `location_neighborhood`, but you will have to double check that.

https://archives.bmlt.app/crouton/crouton-build266-ae913c9b1ac9660bb9edd5872a62d8e4f0c3e264.zip

**Comment by pjaudiomv** [comment]
cool, just played got the county field added and changed the theme.

**Comment by radius314** [comment]
Thanks for doing that.

**Comment by rogersearle** [comment]
YAY!!  I've got a second address line inserted (location_neighborhood) and can change theme :)  
(I will have follow up question on finer points of making this work)

**Comment by radius314** [comment]
If you want to modify the `formatted_address`, it's essentially this.

```{{ ~this.location_street~ }}, {{ ~this.location_municipality~ }}, {{ ~this.location_province~ }}, {{ ~location_postal_code_1~ }}```

**Comment by radius314** [comment]
There is also some magic that happens to properly format the data.  You can looking into the handlebars.js documentation which is what is being used behind the scenes.

**Comment by radius314** [comment]
released in 3.4.1
