### ISSUE TITLE
Custom Theme Submission Request

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/crouton#155]
#bmlt-tabs {
    font-family: "Open Sans","Helvetica",sans-serif;
}

#bmlt-tabs .bmlt-header,
#bmlt-tabs .bmlt-page {
    background-color: transparent;
}

.entry-content #bmlt-tabs ul {
    padding: 0 0 23px 0;
}
.bootstrap-bmlt .nav-tabs>li {
    margin-right: 5px;
}
#bmlt-tabs .nav-tabs > li > a {
    border-radius: 0;
    padding: 6px 12px;
    font-size: 1.25em;
    background-color: transparent;
    border: 2px solid #ccc;
}
#bmlt-tabs .nav-tabs > li > a:hover {
    color: #DB4865;
}
#bmlt-tabs .nav-tabs > li.active > a, #bmlt-tabs .nav-tabs > li.active > a:hover, #bmlt-tabs .nav-tabs > li.active > a:focus {
    background-color: #DB4865;
    border: 2px solid #ccc;
    border-bottom-color: #ccc;
}
#bmlt-tabs .bmlt-button-container {
    margin-right: 5px;
}
#bmlt-tabs #day.btn-sm, #bmlt-tabs #city.btn-sm {
    padding: 6px 12px;
    border-radius: 0;
}
#bmlt-tabs .bmlt-header .bmlt-dropdown-container:nth-child(3) {
    margin-left: 10px;
}

.select2-container--default .select2-selection--single {
    border-radius: 0;
    border: 1px solid #ccc;
}
@media screen and (max-width: 991px){
    #bmlt-tabs .nav-tabs > li > a {
        padding: 5px;
        font-size: 1.1rem;
    }
}

**Comment by radius314** [comment]
picking this up now.

**Comment by radius314** [comment]
will be in crouton 3.4.0 and available in the next build.

**Comment by radius314** [comment]
@klgrimley not sure if this the desired look, but it looks a little off on narrower displays

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1850811/65835210-a3ff0a00-e2b1-11e9-8fcf-126164bb989a.png">

**Comment by pjaudiomv** [comment]
https://archives.bmlt.app/crouton/crouton-build268-ed440d6e130b191928303092e59cf108385290a8.zip

WordPress crouton build

**Comment by klgrimley** [comment]
Edited my original post to include the media query for the smaller display sizes.

**Comment by radius314** [comment]
the update will be released in the next version

**Comment by radius314** [comment]
This was released in 3.4.2
