### ISSUE TITLE
3.4.0-beta1 location_postal_code_1

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/crouton#156]
**Describe the bug**
{{this.location_postal_code_1}} Doesn't pull in zip

**To Reproduce**
1. Go to https://centralindianana.org/meetings/
2. None of the meeting address are displaying a zip code

**Desktop (please complete the following information):**
 - OS: mac 10.14.4
 - Browser: chrome
 - Version: 77.0.3865.90

**Smartphone (please complete the following information):**

**Additional context**

**Comment by radius314** [comment]
Can you include the full value of your "Meeting Data Template"?

**Comment by klgrimley** [comment]
`<div class='meeting-name'>{{this.meeting_name}}</div><div class='location-text'>{{this.location_text}}</div><div class='meeting-address'><address>{{this.location_street}}<br>{{this.location_municipality}}, {{this.location_province}} {{this.location_postal_code_1}}</address></div><div class='location-information'>{{this.formatted_location_info}}</div>`

**Comment by radius314** [comment]
I looks like the postal code is visible in some cases, but not in others.

**Comment by radius314** [comment]
One of these has a zip.

![image](https://user-images.githubusercontent.com/1850811/65835655-fc84d600-e2b6-11e9-9f94-0c95bbe74f88.png)

**Comment by klgrimley** [comment]
Yes. Going to check some things to see if it's an issue on my end.

**Comment by klgrimley** [comment]
Issue is on my end. Not all meetings have a zip entered. Just didn't realize how many didn't. Sorry
