### ISSUE TITLE
3.4.0-beta1 Custom Themes

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/crouton#157]
**Describe the bug**
Custom theme overrides styles in child theme style.css

**Expected behavior**
WordPress child theme style.css should be the last stylesheet loaded on a page. The crouton theme stylesheets are loaded just prior to the closing </body> tag.

**Comment by radius314** [comment]
This works exactly the same as Custom CSS feature.  It just loads an external CSS versus embedding in the page in `<style>` tag.  I can rename Jack to default if you feel that makes sense.

**Comment by radius314** [comment]
Or some indicator which says `jack` is the default.

**Comment by radius314** [comment]
@klgrimley would this work?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1850811/65835828-fb54a880-e2b8-11e9-98bc-d65651560771.png">

**Comment by klgrimley** [comment]
Yeah, I think th default indicator you just added would be helpful. I only noticed it now because it was the first time there were other theme options. I actually never used the in plugin custom css box. Just did it all in the child theme style.css file. I'm probably one of the few that did it that way so I imagine there won't be many issues. 

However, I'd flip the load order of the theme and custom css box. That way some some can choose a theme and then add additional custom css to override it. Currently the theme loads after the custom css.

**Comment by radius314** [comment]
The custom CSS box was added before themes existed.  It was the way that people made custom themes.  The themes feature brings the custom css into a collaborative marketplace.  

I think what you say makes sense in terms of swapping the order.

**Comment by klgrimley** [comment]
Yeah, for most people they're probably going to want a different color or slightly larger/smaller font size. So if the mostly like a theme having the custom css box load after on the frontend means they don't have to add extra specificity or !important (shudders)

**Comment by radius314** [comment]
It's building... https://travis-ci.org/bmlt-enabled/crouton

**Comment by klgrimley** [comment]
Thanks, I know that was pretty nit picky and appreciate you taking the time.

**Comment by radius314** [comment]
Actually it wasn't I feel.  What you said makes a ton of sense and I wouldn't have thought about it.

Here is the latest roll-up build.

https://archives.bmlt.app/crouton/crouton-build269-16a456ab59abaabee97774478cfdc79a5c136438.zip

**Comment by klgrimley** [comment]
Just tried it and it looks good on my end. You'll probably be getting another theme request when I get the chance to rewrite some of it. Did it a few years ago and it needs updated.

**Comment by radius314** [comment]
Sounds good.
