### ISSUE TITLE
Add key for language flag

### ISSUE THREAD

**Issue by otrok7** [bmlt-enabled/crouton#160]
Please see https://na-berlin.de/de/meetings/ for an example of how this could work (this extension of the tabbedUI is a bit older than crouton, and specific for our needs, but it would be nice to be able to use the standard.

This should make use of the format_type_enum and the key for the language being the 2 letter code (eg English is "en", French "fr" etc)

**Comment by radius314** [comment]
Can you explain how this would work?

**Comment by otrok7** [comment]
If the meeting doesn't have any formats of type LANG [flag] is replaced with the empty string.  If the meeting does have a format of type LANG, [flag] is replaced by an <img> tag.  The src attribute somehow has the format key coded into it eg: "../lang/<fmt>/flag.png". 

For this this to work, there has to be some standardization of the format keys:  ISO 639-1 codes being the obvious choice.  But of course its also pretty cheap to have a few extras for common usages... eg I thing some areas use "Sp" for Spanish not "es".

The real logic also needs to handle bi-lingual meetings.

**Comment by radius314** [comment]
There seems to be two features coupled into this issue.

1) The language spoken at the meeting, and also displaying some flag icons(s).
2) Displaying the formats in different languages.

Could it be that there is a default and you can switch out the language depending upon who are?

**Comment by otrok7** [comment]
I think the formats language should follow the language attribute in the shortcode, but this doesn't seem to work.  I will enter it as a bug.  

My experience is that it's good to have the meeting display based on the shortcode (that is, which page you are on) and not on the language of the meeting.  This is a little bit based on the recent German experience.  At first we had eg, the Farsi meeting list only in Farsi.  But the social workers in refugee centers were the ones sending people to NA, and they needed to see the meetings in German, and then explain (over a translator) where the people should go.  So listing the Farsi meetings in Farsi didn't do any good.  Same with the helplines.

**Comment by radius314** [comment]
How are flags related to language?

**Comment by otrok7** [comment]
You're right that there is in fact an m:n mapping, and so theoretically, flag symbol is unclear.  Isn't it common practice, eg,  it is used by plugins like Polylang.  And I know that people from Australia and the US that come to visit Berlin have had no problem understanding that the Union Jack meant that these are the meetings where they will understand what is being said.

Because flags are colorful they are easy to spot...and that is really the point.  This "format" is something that is particular relevant, and I think it is too important to be displayed with a 2 letter symbol with whether or not the Just for Today is read, at least that's really the motivation behind this ticket.

That said, it is probably more correct to print the language...just be sure to do that *in the language*.  That is, it doesn't do any good to write "Farsi" for Farsi meetings, you have to use the Farsi characters,

**Comment by radius314** [comment]
Sounds like a styling preference, which is totally do-able now without any further changes.

You could for instance, inject a `<span>` element into the Meeting Data Template, and reference the meeting formats special variable as the class names.  Example:

```html
<div class='meeting-name'>{{this.meeting_name}}</div><div class='location-text'>{{this.location_text}}</div><div class='meeting-address'>{{this.formatted_address}}</div><div class='location-information'>{{this.formatted_location_info}}</div><span class='format-flag {{formatDataPointerFormats this.formats_expanded}}'></span>
```

This then gets rendered as something like?

```html
...
<span class="format-flag 1--woche-d-xn---monats--auch-nichtschtige-willkommen-h4d deutsch"></span>
...
```

If you prefer to use the abbreviation codes you should be able to do this:


Then in the custom_css (or use a theme that you might create to share), you could add in references to all the languages that might utilize a flags image sprite.

```css
.format-flag.deutsch {  ... }
```

You could also just get the abbreviations using:

```{{formatDataKeyFormats this.formats_expanded}}```

If there is some other combination you are trying to do, let me know.

**Comment by radius314** [comment]
As far as printing the language in the language that is something else I will explore.

**Comment by radius314** [comment]
> Sounds like a styling preference, which is totally do-able now without any further changes.
> 
> You could for instance, inject a `<span>` element into the Meeting Data Template, and reference the meeting formats special variable as the class names. Example:
> 
> ```
> <div class='meeting-name'>{{this.meeting_name}}</div><div class='location-text'>{{this.location_text}}</div><div class='meeting-address'>{{this.formatted_address}}</div><div class='location-information'>{{this.formatted_location_info}}</div><span class='format-flag {{formatDataPointerFormats this.formats_expanded}}'></span>
> ```
> 
> This then gets rendered as something like?
> 
> ```
> ...
> <span class="format-flag 1--woche-d-xn---monats--auch-nichtschtige-willkommen-h4d deutsch"></span>
> ...
> ```
> 
> If you prefer to use the abbreviation codes you should be able to do this:
> 
> Then in the custom_css (or use a theme that you might create to share), you could add in references to all the languages that might utilize a flags image sprite.
> 
> ```css
> .format-flag.deutsch {  ... }
> ```
> 
> You could also just get the abbreviations using:
> 
> `{{formatDataKeyFormats this.formats_expanded}}`
> 
> If there is some other combination you are trying to do, let me know.

@otrok7 did you get a chance to try this out?

**Comment by radius314** [comment]
Hey I noticed that your format codes do not exist for `fa` yet.  Is this in progress?

**Comment by radius314** [comment]
The format feature is working now , btw.  It takes the first two letters of the `language`.
