### ISSUE TITLE
Add Farsi

### ISSUE THREAD

**Issue by otrok7** [bmlt-enabled/crouton#164]
{
			"days_of_the_week" :  [
""
'یَکشَنبه',
'دوشَنبه',
'سه‌شنبه',
'چهار شنبه', 
 'پَنج شَنبه', 
'جُمعه', '
 'شَنبه'
]
                 "weekday" : "روز هفته" :                       
			"city" : "شهر" :                                  
			"cities" : "شهرها" :                            
			"groups" : "گروه ها" :                          
			"areas" : "نواحی"                              : 
			"locations" : "آدرسها" :                     
			"counties" : "بخشها" :                        
			"states" : "ایالات" :                            
			"postal_codes"                                "کد پستی" :
                 "Zips", "زیپ ها" :                                       
			"formats" : "فورمت ها" :                       
			"map" : "نقشه" :                                    
		},

Translations courtesy Meysam, for Iranian fellowship

**Comment by radius314** [comment]
thanks
