### ISSUE TITLE
Modal on map isn't translated to language picked in url or shortcode

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#165]
When the meeting icon on the map is clicked the date and time should follow the shortcode parameters and the "map to meeting" should be translated.
![crouton_popup](https://user-images.githubusercontent.com/31661648/67778836-cfe8e900-fa31-11e9-8f3d-680cde2252d6.png)

**Comment by radius314** [comment]
will be in 3.4.5
