### ISSUE TITLE
additional format info not working for localization

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#172]
**Describe the bug**
for 3.4.5 

**To Reproduce**
set crouton to separate language ex `[bmlt_tabs language="de-DE"]`
click on formats tooltip and get blank tooltip

**Expected behavior**
format descriptions show up

**Screenshots**
![Screen Shot 2019-11-03 at 6 06 05 PM](https://user-images.githubusercontent.com/34245618/68093547-a4686300-fe64-11e9-8582-38510574f31c.png)
![Screen Shot 2019-11-03 at 6 05 52 PM](https://user-images.githubusercontent.com/34245618/68093548-a500f980-fe64-11e9-906b-e873b04785ea.png)

**Additional context**
doesn't work on croutonjs either

**Comment by radius314** [comment]
This is the call that is made when the language is set.  Could it be that there are no `de` versions of your formats?

https://www.nerna.org/main_server/client_interface/json/?switcher=GetFormats&lang_enum=de

**Comment by pjaudiomv** [comment]
ahh was wondering how that worked, so it uses the first two digits to get lang_enum for formats.

**Comment by radius314** [comment]
yes, it's a calculated configuration value called `short_language`.

you should be able to see that in the javascript console `crouton.config['short_language']`
