### ISSUE TITLE
Add ability to add telephone number and email contact info

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#173]
Italian Region would like to be able to display their meeting telephone number and email contact information below the address to the meeting.

**Comment by radius314** [comment]
You should be able to do this already with the template feature. Keep in
mind that those fields are hidden by default and will have to be made
public.

**Comment by californiasteve** [comment]
Is there any documentation on this?

**Comment by californiasteve** [comment]
Found it
