### ISSUE TITLE
Possible to set a default city selection?

### ISSUE THREAD

**Issue by nonsub** [bmlt-enabled/crouton#182]
Thanks for this great work!

Is there a way (code edit if necessary) to have a default city selected?

cheers

**Comment by radius314** [comment]
What's the use case?

**Comment by nonsub** [comment]
The use case is that is that we might want to make our capital city (in this case Winnipeg,) the first listing as this is where the majority of our meetings and where the majority of our site visitors are. Now that I think about this I suppose justification is not strong! I could also do this I believe by having a pre-selection (checkbox or radio button for Winnipeg only) and (I think?) a custom query.

Thanks!

**Comment by radius314** [comment]
You could have different links for each city and then pass that a querystring parameter.  Crouton will automatically pick these up and apply them as overrides to your shortcode.  Custom queries give you a lot of flexibility.

**Comment by nonsub** [comment]
Thank you radius! Not sure what protocol is here for self-closing issues but I'm satisfied. Thanks!

**Comment by radius314** [comment]
Also the next version of crouton (3.5.0) will allow you to start with a map search.  In this case you could say to give the 50 closest meetings to Winnipeg, or meetings with in 20km.  Or anything else you can think of.
