### ISSUE TITLE
Duplicate meeting code descriptions? (Must be related to root server?)

### ISSUE THREAD

**Issue by nonsub** [bmlt-enabled/crouton#183]
For whatever reasons some databases (well at least one) have multiple instances of format selections. In this example they must have multiple duplicate selections for both No Smoking and Closed and what happens is that if you have say 49 meetings where you enabled the first instance of the option but on the 50th (or any number) meeting you for some reason chose the second instance of that setting you will end up with a duplicate entry in the legend and drop down.

So I think this needs to be "fixed" on the roots but a possible workaround might be to do a check for duplicate text and not include? It does appear that the codes themselves are only listed once in the legend?

Thanks!

**Comment by radius314** [comment]
Which root server?

**Comment by nonsub** [comment]
Hi Radius. Thanks for the reply. https://canaacna.org/meetings/main_server/

Here is an example (Closed and No Smoking) are duped: 
https://bcrna.ca/index.php?category=meetings

I can confirm there are duplicate format options in admin (quite a few more than the above two.)

**Comment by radius314** [comment]
This is a data issue with that root server.  This happened likely as a result of the merging of Quebec into the CANA server, the formats needs to be consolidated.

**Comment by nonsub** [comment]
Thanks. Yeah that is what I suspected. I will pass this along. Is there any point in moving this to bmlt-root-server to see if consideration might be given to preventative logic on the backend?

**Comment by radius314** [comment]
It's not that simple.  However, the admin for CANA root server reached out to me this morning and we are working together to resolve this as a one off.
