### ISSUE TITLE
js errors with show_map

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#190]
using short code `[bmlt_tabs show_distance="0" show_map="1"]` getting the following error happened testing with both florida and nernas server regardless of configuration of service body

`TypeError: e is not a function crouton.nojquery.min.js:1:318073`

**Comment by radius314** [comment]
fix is in master

**Comment by radius314** [comment]
ready to be tested https://archives.bmlt.app/crouton/crouton-build401-6aba3e68fe22bb378289f4e9cbfa37de4b77abb8.zip

**Comment by radius314** [comment]
Released in 3.5.1
