### ISSUE TITLE
include_city_button="0" does nothing

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#191]
I know 3.3.0 stated croutonjs no longer support `include_city_button` but wordpress should not be affected. however I am on 3.5.1 and `include_city_button="0"` still displays the city button. OIt would be nice to have this feature back either with `include_city_button="0"` or `button_filters_options="-0"` or whatever, just someway to hide the city button.

**Comment by radius314** [comment]
You could do this for now.  

![image](https://user-images.githubusercontent.com/1850811/73990033-e5658d00-4915-11ea-9c39-6570934f05cc.png)

**Comment by pjaudiomv** [comment]
👍

**Comment by radius314** [comment]
in master.  you can do the original `include_city_button="0"` or `button_filters_option=""`

**Comment by pjaudiomv** [comment]
sick, curious will `button_filters=""` work on croutonjs as well

**Comment by radius314** [comment]
button_filters=[]

**Comment by pjaudiomv** [comment]
word

**Comment by pjaudiomv** [comment]
awesome just took it for a spin, working great now. thanks.

**Comment by radius314** [comment]
release in 3.5.2
