### ISSUE TITLE
Add Option for Language Selection for Crouton.js

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/crouton#200]
**Is your feature request related to a problem? Please describe.**
We have a Crouton.js implementation of Virtual NA at https://www.na.org.au/multi/virtual-test/
We would like to have the language default filtering English language meetings but have the option for a drop down so that other languages can also be displayed.  
This seems to be an option on Virtual NA but its missing in the variables options in crouton.js
![image](https://user-images.githubusercontent.com/29008815/74620003-447f9900-5183-11ea-8b8d-7151854a73e4.png)
The following shortcode is what we are using
[bmlt_tabs root_server="https://bmlt.virtual-na.org/main_server/" service_body_parent="4" has_locations="1" has_zip_codes="0" has_cities="0" has_locations="0" has_areas="1" base_tz="UTC" auto_tz_adjust="1"]

**Describe the solution you'd like**
We would like to be able to display English language meetings by default with an option to select other languages just like on Virtual-NA.org

**Describe alternatives you've considered**
We considered using the full Crouton on a different subsite and setting the page to display in a iframe.

**Comment by radius314** [comment]
ok most of this is completed, i need to add an option to set the default language

**Comment by radius314** [comment]
I am going to release this without the default language selection.  I have some concerns with the complexity this is introducing.

**Comment by radius314** [comment]
It seems like before introducing default selections on language it might make sense to have #21 implemented, which is not a trivial change.

**Comment by radius314** [comment]
@brustar64 there is an incoming fix for this https://github.com/bmlt-enabled/crouton/pull/206#issuecomment-599095039

**Comment by radius314** [comment]
will be released in 3.7.0

**Comment by brustar64** [comment]
Awesome! Thanks Danny!
________________________________
