### ISSUE TITLE
header display on/off not working

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#208]
using `header="0"` stopped working in current release. found out using this shortcode `[bmlt_tabs header="0" has_tabs="0"]`

**Comment by pjaudiomv** [comment]
doing just `[bmlt_tabs header="0"]` displays only current day

![Screen Shot 2020-03-15 at 6 45 15 PM](https://user-images.githubusercontent.com/34245618/76712241-20b16380-66ed-11ea-9471-2f3aed713fca.png)

**Comment by radius314** [comment]
looking now

**Comment by pjaudiomv** [comment]
yea i think this issue came up once before too https://github.com/bmlt-enabled/crouton/issues/95

**Comment by radius314** [comment]
What is the behavior that should happen?  I don't remember.

**Comment by radius314** [comment]
should it be what's in #95

**Comment by pjaudiomv** [comment]
yes
https://user-images.githubusercontent.com/34245618/54095369-59ea2180-437d-11e9-8ad1-9d1466202157.png

**Comment by radius314** [comment]
can you review #209?
