### ISSUE TITLE
Keep weekday tabs for each list

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/crouton#21]
It would be nice if we could keep the weekday tabs when selecting a secondary dropdown like "Counties" or "Cities"... So every  display in Crouton would be tabbed by weekday, and then filtered by the drop down list. Does that make sense? Currently when you choose any of the dropdowns, the weekday tabs are lost.

**Comment by pjaudiomv** [comment]
yes this does make sense, it would be a nice option to have. as it can still be a big list once its filtered. although if it isn't a big list once your selection is filtered you may think there are no meetings if the day your on has none from that list. I wonder if we just made this an option and let the user (webservant) decide. or if it were conditional like if it returns at least a meeting for everday leave the days on. idk.

**Comment by paulnagle** [comment]
That sounds great, having this an an option would be ideal

**Comment by radius314** [comment]
this is going to be a little easier to do now that #53 was completed.
