### ISSUE TITLE
Installed new version of Crouton, meetings don't populate

### ISSUE THREAD

**Issue by otwna** [bmlt-enabled/crouton#212]
**Describe the bug**
After installing new crouton version, meetings don't populate and are only blank tables.

Root server: https://nacolorado.org/meetingList/main_server

https://www.otwna.org/meetings/

**Comment by radius314** [comment]
the latest fix isn't working still :(

**Comment by radius314** [comment]
@otwna can you upgrade to 3.8.3 and check?
