### ISSUE TITLE
markers not overlaying on latest version

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#216]
![Screen Shot 2020-03-18 at 9 15 06 PM](https://user-images.githubusercontent.com/34245618/77021686-d08d0800-695d-11ea-973e-a79bd1d5ef82.png)
![Screen Shot 2020-03-18 at 9 16 41 PM](https://user-images.githubusercontent.com/34245618/77021688-d256cb80-695d-11ea-8356-d816f0edd301.png)

**Comment by radius314** [comment]
probably the fix i rolled for IE11 🤦‍♂

**Comment by pjaudiomv** [comment]
oh deer, was there a problem with it. OMS worked with ie11 before. did we bump the version at some point maybe?

**Comment by pjaudiomv** [comment]
this def worked with ie 11 https://github.com/bmlt-enabled/crouton/blob/3.0.0/croutonjs/src/js/oms.min.js

but i see this is what was there https://github.com/bmlt-enabled/crouton/blob/3.8.6/croutonjs/src/js/oms-1.0.3.min.js

**Comment by pjaudiomv** [comment]
ah yes it was added as part of multiple meetings indicator fix https://github.com/bmlt-enabled/crouton/commit/546b5196e52d791c927bdfbb6fe3c0da9a6d2248#diff-20d4cece128d64bc9bcc5f8e3d13869c

**Comment by pjaudiomv** [comment]
if the latest oms is the problem maybe we roll back or add a wordpress specific feature to use if we want to keep latest and still support ie11. I use this on 34 different pages. not having oms isn't bad for small data sets, but it really helps with larger ones.

**Comment by radius314** [comment]
it's not OMS, it's MarkerClusterer.

**Comment by radius314** [comment]
That library doesn't work with IE11.

**Comment by pjaudiomv** [comment]
oh.....

**Comment by pjaudiomv** [comment]
this one did https://github.com/bmlt-enabled/crouton/blob/3.0.0/croutonjs/src/js/markerclusterer.js

**Comment by radius314** [comment]
It does not work correctly.  `class` is not recognized.  Other parts may have worked correctly, but I have no interest in trying to figure that out.  I'm going to look at seeing why this failed.

**Comment by radius314** [comment]
ok that one is different, i'm gonna try that out.

**Comment by pjaudiomv** [comment]
yea I only know it worked fine because  of the k-meleon debacle

**Comment by radius314** [comment]
🔫

**Comment by radius314** [comment]
destined for 3.8.8, being cut now

**Comment by radius314** [comment]
@pjaudiomv is this ok now?

**Comment by pjaudiomv** [comment]
sure is, thanks
