### ISSUE TITLE
text not wrapping and staying in column

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#220]
this is on latest master works fine on 3.8.8

https://archives.bmlt.app/crouton/crouton-build533-5f4265e1a00cc24008e91bbcd11f562ba8322a2b.zip

![Screen Shot 2020-03-27 at 7 57 30 PM](https://user-images.githubusercontent.com/34245618/77809335-8bf02380-7065-11ea-8563-dbba645e3b61.png)

3.8.8

![Screen Shot 2020-03-27 at 7 59 01 PM](https://user-images.githubusercontent.com/34245618/77809360-98747c00-7065-11ea-8714-9d5a17d2a04e.png)

**Comment by pjaudiomv** [comment]
the `white-space: nowrap;` is letting it break out of its container. I think the container needs to be hardened. 

https://github.com/bmlt-enabled/crouton/blob/ea2f52528380e5af403392402fea6dc7e0d2ca97/croutonjs/src/css/bmlt_tabs.css#L109

**Comment by radius314** [comment]
@pjaudiomv does this look good to you now?

**Comment by pjaudiomv** [comment]
👜

**Comment by radius314** [comment]
how about on a mobile device?

**Comment by pjaudiomv** [comment]
yes fine, nice on mobile too
