### ISSUE TITLE
question about shortcode weekday|city

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#225]
Hello everybody

There`s a way to disable aggregator weekday|city botton?
There`s a way to disable map botton?

**Comment by radius314** [comment]
You can hide the weekday button like this;

`[bmlt_tabs button_filters_option=""]`

You can hide both like this;

`[bmlt_tabs button_filters_option="" has_tabs="0"]`

**Comment by radius314** [comment]
Why do you want to hide the map button?

**Comment by abna-brasil** [comment]
> Why do you want to hide the map button?

This is Just a other site test ....
With online Meetings

**Comment by radius314** [comment]
If you set the meeting to VM (Virtual Meeting) it will display the virtual meeting link.  

If you set the meeting to TC it will display as the facility being temporarily closed (if for pandemic reasons).

You can also make a separate page with just virtual meetings and hide it with CSS or make a new metadata template.

Trying to understand what your end goal is.
