### ISSUE TITLE
add ability to only display unpublished meetings

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#229]
in addition to the newly implemented unpublished feature it would be nice to have ability to only display unpublished meetings as opposed to including both published and unpublished

**Comment by radius314** [comment]
How is that accomplished?

**Comment by pjaudiomv** [comment]
int he root server you do `&advanced_published=-1` instead of `&advanced_published=0`

**Comment by radius314** [comment]
in `master` destined for `3.9.5`

**Comment by radius314** [comment]
delivered
