### ISSUE TITLE
Wont display multiple service body meetings

### ISSUE THREAD

**Issue by MikeCatz20** [bmlt-enabled/crouton#230]
**Describe the bug**
Using Version 3.9.5, I cannot get Crouton to display multiple service bodies in its output.
I have 2 service bodies.  I do see the Default service body output only.
I activate one plugin at a time: Changing nothing else on my WP installation other than going between BMLT Tabbed UI Version 6.0.14 and Crouton 3.9.5, the failure shows up.

BMLT Tabbed UI output works fine every time.

All other server, WP, pages, etc. settings stay unchanged.

**To Reproduce**
I simply Deactivate one plugin and switch to the other.
I do have the latest BMLT Server installed Version 2.15.2 when I switch between them.
I have also tried deactivating BMLT Meeting List, and reactivating, then activating Crouton (activate plugin after BMLT Meeting List is deactivated and then reactivated).
My number 1 service body is the default.  I tried using shortcoodes:
bmlt_tabs service_body=2   without success
bmlt_tabs service_body_parent=1,2  without success
Set recurse service bodies, without success.

**Expected behavior**
I expect it to work the same way as BMLT Tabbed UI

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10, Android 10.0
 - Browser [e.g. chrome, safari]  All browsers: Firefox, Chrome

**Smartphone (please complete the following information):**

**Additional context**

More than willing to do a remote session if that would help to triage.
The page I need help with: http://www.gsana.org/meeting-list

Thanks!

**Comment by radius314** [comment]
Can you try this for now as a workaround `[bmlt_tabs custom_query="&services[]=1&services[]=2"]`

**Comment by pjaudiomv** [comment]
actually try this `[bmlt_tabs custom_query="&services%5B%5D=1&services%5B%5D=2"]`

**Comment by MikeCatz20** [comment]
Thanks guys for your responses!
I tried both. Same issue. Im changing this on an existing page.
BUT....
I just created a new page, added the shortcode, and it WORKS on that new page!!
But wont work on the old page.  I'm clearing my browsers cache (not that it should matter), but is there some sort of internal caching or stuck flag based on source page name/id going on someplace?

**Comment by MikeCatz20** [comment]
Ok, found it.  
If a page has a short code of [group_count] prior to additional shortcodes, this problem occurs.
If I take the group_count out, it works. Put it back in, it fails.

**Comment by radius314** [comment]
I think we should leave this open.  There are some improvements that can be made around having multiple short codes on the page.  Right now there are some optimizations that are probably limiting some capabilities.

**Comment by radius314** [comment]
I could not repro the issue of having `[group_count]` before `[bmlt_tabs]`.

**Comment by MikeCatz20** [comment]
My config:

BMLT Server has 2 service bodies. Default service body to display is "1"
Page has a [group_count] at the top.
Later in page, I have [bmlt_tabs service_body="2"]
 
The meeting list displayed shows service body 1, not anything from 2.

**Comment by radius314** [comment]
Seems fine.  
![image](https://user-images.githubusercontent.com/1850811/79676461-86917f00-81b4-11ea-8c10-03bf4583b371.png)

**Comment by radius314** [comment]
![image](https://user-images.githubusercontent.com/1850811/79676467-95783180-81b4-11ea-92be-d47d403cac5a.png)
