### ISSUE TITLE
Root server 

### ISSUE THREAD

**Issue by jefwheels** [bmlt-enabled/crouton#233]
**Describe the bug**
Connection to Root Server Failed. The URL is accessible in a browser but not in the crouton settings for default Root Server. 
https://nerna.org/main_server
I can user Tomato and other BMLT Root Servers but not this one. 
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbraswell** [comment]
I'm not tracking the issue here.

Specifically, I don't know what this means:

> The URL is accessible in a browser but not in the crouton settings for default Root Server.

Do you have screenshots?

**Comment by jefwheels** [comment]
The BMLT Root sever URL should be https://nerna.org/main_server  This is the root server to our region. Service Body 671

Right now I have to user tomato because the above does not work for my wordpress site. This use to work.

It’s almost like they are blocking us somehow. I can use https://tomato.bmltenabled.org/main_server

But it takes to long for the page of meetings about 5-6 seconds to load. 

Any help would be greatly appreciated. 

 

Thanks

**Comment by radius314** [comment]
You should contact the server administrator for that root server and ask them if they are seeing it blocked.  Other than that, this does not appear to be a crouton issue.

**Comment by jefwheels** [comment]
Thanks. That’s exactly what it was.
