### ISSUE TITLE
how to get phone number from bmlt using crouton?

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#234]
Hello friends,

There´s a code [crouton_map] or [bmlt_tabs] like has_groups to get listed the phone number filed on other tab, during registration meeting registration on Contact 1 Phone field?

![bmlt_tab](https://user-images.githubusercontent.com/61021590/81627705-27024a00-93d5-11ea-8ac0-229609662be1.JPG)

**Comment by radius314** [comment]
What are you using this field for?  Usually this field is for someone's personal phone number.

**Comment by abna-brasil** [comment]
Hello 

We are using this fild to publish the Help Line Phone Number who answer for this meeting area.
Thats why we´d like to show it on crouton.

**Comment by radius314** [comment]
By default these fields are hidden on the root server.  Have you taken a look at using Yap?

**Comment by abna-brasil** [comment]
Yes,
We´d love to use YAP too... 
But this feature we need to show our help lines' numbers on our page...
Do you sugest another way to show it using croutnon?

**Comment by radius314** [comment]
I would suggest using some other field that is not being used.  Once you do
that you can modify the metadata template to include it.  (For example:
train lines or bus lines)

**Comment by abna-brasil** [comment]
Got you

**Comment by abna-brasil** [comment]
If we chose bus line for example...
how get it using crouton?

**Comment by radius314** [comment]
You could modify either the meeting data or metadata template to include it.  See the screenshot below.  You would reference by `{{this.bus_lines}}` and add an additional `<div>`.

![image](https://user-images.githubusercontent.com/1850811/82352684-5106ce00-99cc-11ea-9b10-65963fc0665f.png)

**Comment by abna-brasil** [comment]
Radius
tks for help...
We finally set up a yap server!!! I'll open a ticket about it on yap session!
tks again
Roger
