### ISSUE TITLE
Virtual Meetings

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/crouton#235]
Link and phone number for virtual meetings are displaying on my online meeting schedule, but not with the print meeting list generated by Bread. Bread issue or Crouton issue?
Any help with this?

**Comment by radius314** [comment]
From the description it's not clear what you mean by "online meeting schedule".

**Comment by DanielWright98** [comment]
The BMLT schedule on the website. It show virtual meetings but the links don't appear when we generate the schedule in Bread.

**Comment by radius314** [comment]
Bread is unrelated to Crouton and vise-versa.

**Comment by DanielWright98** [comment]
Sorry to bother you.
