### ISSUE TITLE
speed up loading time when using tomato

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#238]
currently crouton loads all the service bodies and formats, this can take a long time when using tomato. to speed up we could only load needed service bodies like so

this would load only service bodies in new england region
https://www.nerna.org/main_server/client_interface/json/?switcher=GetServiceBodies&services=1&recursive=1

or this will load only a single service body for marthas vineyard

https://www.nerna.org/main_server/client_interface/json/?switcher=GetServiceBodies&services=8

to speed up formats we could only get the used formats from query like so, this gets only the used formats from marthas vineyard

https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&services=8&get_formats_only

this would get the meeting results with formats appended to the end

https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&services=2&get_used_formats

**Comment by pjaudiomv** [comment]
this is would require root server version 2.15.3 which hasn't even been released yet however tomato does have this feature and is the main thing trying to speed up.

**Comment by radius314** [comment]
If someone hasn’t upgraded what would happen?  Is this backward compatible?

**Comment by pjaudiomv** [comment]
for tomato it is, like it doesn't matter what version a root server is that gets imported into tomato, the queries still run fine.

**Comment by pjaudiomv** [comment]
the format queries have been in root server for long time.

**Comment by pjaudiomv** [comment]
well it kind of is backwards compatible in a way for regular root services, if you run `GetServiceBodies&services=1&recursive=1` or `GetServiceBodies&services=8` on a root server that doesnt have that feature its just gonna give you every service body in server

**Comment by radius314** [comment]
are you self assigning or only making a feature request?

**Comment by pjaudiomv** [comment]
I'm assigning you :)

**Comment by radius314** [comment]
Will this new endpoint support multiple `services` params?

**Comment by pjaudiomv** [comment]
Yes

**Comment by pjaudiomv** [comment]
For instance this would give you Martha’s Vineyard and Nanfucket https://www.nerna.org/main_server/client_interface/json/?switcher=GetServiceBodies&services%5B%5D=8&services%5B%5D=10

**Comment by radius314** [comment]
Thanks.

**Comment by radius314** [comment]
It's actually easier in crouton to pass all the services rather than have logic to determine if `recursive` is required.

**Comment by radius314** [comment]
Is it possible to call `GetFormats` and pass the `services` querystring param?

**Comment by radius314** [comment]
Here is what crouton would currently do.  

https://.../main_server/client_interface/jsonp/?switcher=GetFormats&services[]=44&services[]=45&lang_enum=en&callback=jQuery112409051408423940386_1590185177374&_=1590185177377

There are essentially 3 HTTPS calls made.  First to get the meetings, then to get the service bodies details and then formats.  Are you saying that we could just make one call for getting the meetings and the formats and reduce by one call?

**Comment by pjaudiomv** [comment]
Yes you could get meeting and formats in one call. So it'd be reduced to two calls however they would be optimized by not getting everything

**Comment by radius314** [comment]
#239 has been opened.  It will not only implement your recommendation, but also we would have eliminated one entire HTTPS call by including the formats in the GetSearchResults request.

**Comment by radius314** [comment]
There was a bug found on Tomato which would hold up this release https://github.com/bmlt-enabled/tomato/issues/84.
