### ISSUE TITLE
Make it more apparent when search criteria didn't return results

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/crouton#251]
It can happen during the set up of crouton (especially with custom queries) that no results are returned.  Right now only a javascript console error appears.  It would be nice to see that upfront in HTML on the page to help make it more clear for debugging.

**Comment by tempsaint** [comment]
This would be awesome. Something simple - "Your Search Returned No Results" - would be great. 
Thank you.

**Comment by radius314** [comment]
![Screen Shot 2020-06-25 at 10 44 04 PM](https://user-images.githubusercontent.com/1850811/85815090-82925800-b735-11ea-81f1-d3e901523094.png)
