### ISSUE TITLE
Since the latest updates, crouton does not display meetings on any websites.

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#254]
We loose the display of our meetings on our websites since the latest update.

The only thing we can see on the meeting page is the message "Fetching".

https://naquebec.org/trouver-une-reunion/
https://csr.naquebec.org/trouver-une-reunion/
https://na-outaouais.org/reunions/

Can I test the previous update?

**Comment by radius314** [comment]
reviewing this now.  you can roll back to the previous version https://github.com/bmlt-enabled/crouton/archive/3.10.1.zip

**Comment by radius314** [comment]
I have a fix for this coming now, will be in `3.11.1`.

**Comment by radius314** [comment]
`3.11.1` is released, please attempt to update to this version.
