### ISSUE TITLE
improve documentation and maybe error checking for short code parameters

### ISSUE THREAD

**Issue by alanborning** [bmlt-enabled/crouton#265]
If you have a page with these shortcodes and parameters:

```
[meeting_count]
[bmlt_tabs include_unpublished="1"]
```

then the default for `include_unpublished` (which is 0) will apply to `meeting_count`, and also silently override the explicit parameter for `bmlt_tabs`. The silent overriding tripped me up .... it's obvious in retrospect what was happening, but wasn't while trying to figure it out.

To help future users with this, minimally we could add something to the documentation for "crouton Shortcode Usage" about watching out for this. (I could submit a pull request with that.) A more robust fix would be to also check for an explicit parameter to a shortcode that was going to be ignored.

**Comment by radius314** [comment]
I have assigned you the issue and made you a contributor.
