### ISSUE TITLE
Please we want to use fields marked "This is never displayed in normal meeting searches."

### ISSUE THREAD

**Issue by gingerwatch** [bmlt-enabled/crouton#268]
Currently the "OBSERVER" user can only see information in hidden fields (those marked "This is never displayed in normal meeting searches.") if they are signed in to the ROOT SERVER (like at https://my/root/server/main_server/).

We would like our local OBSERVERS, who can only see meeting information but not make changes, to view hidden information.  The original intent of Observers was so that people manning the Help Line other such trusted servants could have extra info not available to the viewing public.  This is a perfect use of the Observer position, and use of the hidden information.

Currently our Observers do enjoy the different layout and map with pins they get when logging in to our local BMLT server.

But we would love to make use of those hidden fields to include secret info like "Tom R. holds the key to the church, his number is xxx-xxx-xxxx" Or "Lisa F. lives nearby and is willing to give rides, her number is xxx-xxx-xxxx".

**Comment by radius314** [comment]
@jbraswell do you have a list of these fields that are hidden (stock fields)?  Or is there a way to query that dynamically (even better)?

**Comment by jbraswell** [comment]
Let me fire up the craptop and figure out the best way to track them down.

**Comment by jbraswell** [comment]
```
mysql> select `key` from sezf4_comdef_meetings_data where meetingid_bigint=0 and visibility=1;
+-----------------+
| key             |
+-----------------+
| contact_phone_2 |
| contact_email_1 |
| contact_phone_1 |
| contact_email_2 |
| contact_name_1  |
| contact_name_2  |
+-----------------+
6 rows in set (0.00 sec)
```

**Comment by gingerwatch** [comment]
Thanks for all your help!  Does this mean Observers will get to see the hidden info?

**Comment by jbraswell** [comment]
Yes. They may have to go to a different place to see it for now, but that's the idea.

**Comment by radius314** [comment]
@gingerwatch how does this look to you? 

![Screen Shot 2020-07-11 at 2 31 10 PM](https://user-images.githubusercontent.com/1850811/87231280-e0ed4680-c383-11ea-811d-57f269e1145b.png)

**Comment by gingerwatch** [comment]
It looks GREAT!  But ... did you realize the Observer currently gets a different layout?  I don't know if you want to work within the layout that an Observer currently gets.  It is a different look than what you are showing here.  It has a map with pins at the top, and meeting info in rows below the map.

**Comment by jbraswell** [comment]
@gingerwatch this is intended to be a complete replacement for the existing observer view. The existing one is super old and mostly broken, so we wanted to replace it with something more modern and maintained.

**Comment by radius314** [comment]
As @jbraswell mentioned we will swap out the current display.  I will be sure to include the map with the pins on that view.

**Comment by gingerwatch** [comment]
You guys are like Gods.  I never thought all this would be possible.  The phone line was liking the map with pins.
This is so unbelieveable.  Maybe I can learn some code and help you guys.  I'm taking online Wordpress classes now.

**Comment by alanborning** [comment]
Hey @gingerwatch - one place to start getting involved might be the BMLT documentation project. It looks like a new set of docs is being written using WordPress - so that could make use of your new knowledge! (I'm not working on that part of the project myself but I see it going on.)

**Comment by gingerwatch** [comment]
So has this happened yet?   When logging in as Observer - I still have the old view, missing the hidden info.  Maybe it'll take awhile to get the update?   We have a PR meeting tomorrow so I thought I'd check in so I can bring info back to the committee.

**Comment by jbraswell** [comment]
We cut a new release (2.15.4), and the release has this feature, but we haven't officially announced it yet.

You won't get the update until your BMLT root server administrator installs it. You can get the feature now, but your admin will need to upgrade to 2.15.4.

**Comment by gingerwatch** [comment]
Understood, thank you.
