### ISSUE TITLE
Header for in-person meetings

### ISSUE THREAD

**Issue by TheRichWoods** [bmlt-enabled/crouton#273]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A message in the third column that says 'MEETS IN-PERSON'

**Describe alternatives you've considered**
Another message that means the same thing

**Additional context**
Meetings with VM and HY formats have headers in that section, such as 'MEETS VIRTUALLY' and 'MEETS VIRTUALLY AND IN-PERSON', respectively. If it's an in-person meeting, however, it only shows a map link, which might be confusing. This was designed before virtual and hybrid meetings were being added.

**Comment by radius314** [comment]
This may have already been addressed in a prior fix.  Have you tried
resetting your templates?

**Comment by rwoods716** [comment]
I just tried it and it didn't work.

**Comment by radius314** [comment]
Please include specific examples.

**Comment by TheRichWoods** [comment]
Link to image here: https://1drv.ms/u/s!AuXdMWflJ0J-v8V41MltRhKyS4VJZQ
Link to website: https://www.longislandna.com/meeting-search/

Meetings that meet virtually, or meet virtually and in-person are clearly labelled. In-person meetings are not labelled at all.

**Comment by radius314** [comment]
Ok I see what you are saying.  How would one indicate it's a face-to-face meeting?

**Comment by TheRichWoods** [comment]
I was thinking just adding the header 'MEETS IN-PERSON'. It fits the style of the already existing 'MEETS VIRTUALLY' and 'MEETS VIRTUALLY AND IN-PERSON'.

**Comment by radius314** [comment]
Generally speaking, I do not think it makes sense at this point to make this stock functionality until it’s clear what the world looks like post pandemic.  That being said you have full freedom to modify the metadata template for your own purposes.  

Also given how the implementation of the value “MEETS IN-PERSON” would have to be extrapolated for multi-lingual support, there isn’t a clear path yet on how to use the root server to make flexible resource definitions.

Here is an example of what you can do that would satisfy your needs.

{{#unless (hasFormats 'VM,HY,TC' this)}}<div class='meetsVirtually'><span class='glyphicon glyphicon-user'></span> MEETS IN-PERSON</div>{{/unless}}
{{#isVirtual this}}{{#isHybrid this}}<div class='meetsVirtually'><span class='glyphicon glyphicon-cloud-upload'></span> {{meetsHybrid this}}</div>{{else}}<div class='meetsVirtually'><span class='glyphicon glyphicon-cloud'></span> {{meetsVirtually this}}</div>{{/isHybrid}}{{#if this.virtual_meeting_link}}<div><span class='glyphicon glyphicon-globe'></span> {{webLinkify this.virtual_meeting_link}}</div>{{#if this.show_qrcode}}<div class='qrcode'>{{qrCode this.virtual_meeting_link}}</div>{{/if}}{{/if}}{{#if this.phone_meeting_number}}<div><span class='glyphicon glyphicon-earphone'></span> {{phoneLinkify this.phone_meeting_number}}</div>{{#if this.show_qrcode}}<div class='qrcode'>{{qrCode this.phone_meeting_number}}</div>{{/if}}{{/if}}{{/isVirtual}}{{#isNotTemporarilyClosed this}}{{#unless (hasFormats 'VM' this)}}<div><a id='map-button' class='btn btn-primary btn-xs' href='https://www.google.com/maps/search/?api=1&query={{this.latitude}},{{this.longitude}}&q={{this.latitude}},{{this.longitude}}' target='_blank' rel='noopener noreferrer'><span class='glyphicon glyphicon-map-marker'></span> {{this.map_word}}</a></div><div class='geo hide'>{{this.latitude}},{{this.longitude}}</div>{{/unless}}{{/isNotTemporarilyClosed}}
