### ISSUE TITLE
Change button_filters_option to button_sort_option

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/crouton#277]
The button that's created by the button_filters_option is more of a "sort" feature than a "filter" feature. Maybe it should be changed to more accurately reflect that?

**Comment by radius314** [comment]
It’s really a group by. Changing options means breaking someone’s installation potentially. We have routinely avoided this. My recommendation would be not to change this, as there is little benefit.

[Danny Gershman - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=nkxiz)	[nkxiz]

On August 24, 2020 at 21:28 GMT, Adam Hechler <notifications@github.com> wrote:

The button that's created by the button_filters_option is more of a "sort" feature than a "filter" feature. Maybe it should be changed to more accurately reflect that?
