### ISSUE TITLE
BMLT Tabs custom query (format meeting code) does not work

### ISSUE THREAD

**Issue by odathp** [bmlt-enabled/crouton#279]
The shortcode  [bmlt_tabs custom_query="&formats=55&services=2"] does not work.

The shortcode  [bmlt_tabs custom_query="&formats[]=55&services=2"] does not work.

The shortcode [bmlt_tabs custom_query="&formats%5B%5D=55&services=2"] does not work.

[bmlt_tabs custom_query="&formats%5B%5D=55"] does not work

[bmlt_tabs custom_query="&formats=55"] does not work

Root Server = https://naflorida.org/bmlt_server (Version 2.15.1)
Greater Orlando Area Service Body = 2
Virtual Meeting Code = 55

The following works:

![image](https://user-images.githubusercontent.com/960391/92138424-94464a80-edcb-11ea-9741-875956539b95.png)

Could you test this on the latest version of the root server? Perhaps that's where the solution lies...

**Comment by pjaudiomv** [comment]
is the tabbed ui plugin disabled, can you post a link to the site you are having issues with.

**Comment by floydwonder** [comment]
Following up on this for https://orlandona.org/virtual-meetings/ 

Our website is one Jack was referring to.

**Comment by radius314** [comment]
Taking a look now @floydwonder

**Comment by radius314** [comment]
Try changing the custom_query shortcode to `formats%5B%5D=341&services%5B%5D=128`.  This would cover virtual meetings.

**Comment by floydwonder** [comment]
Thank you! Our virtual meetings page is working again.

Could you also assist us by providing the custom query shortcode for these as well? 
https://orlandona.org/hybrid-meetings/ 
https://orlandona.org/in-person-meetings/ ?

**Comment by radius314** [comment]
Hybrid: `formats%5B%5D=342&services%5B%5D=128`
In Person: `formats%5B%5D=-340&services%5B%5D=128`

**Comment by floydwonder** [comment]
Thanks again - we appreciate your service! 

Looks like everything is working now.

**Comment by odathp** [comment]
> 
> 
> Following up on this for https://orlandona.org/virtual-meetings/
> 
> Our website is one Jack was referring to.
Yes thanks for the plug,  Eric

**Comment by odathp** [comment]
> 
> 
> Hybrid: `formats%5B%5D=342&services%5B%5D=128`
> In Person: `formats%5B%5D=-340&services%5B%5D=128`

Hi, I didn't know if anyone knew that Jack passed away,  I was a friend recovering some of his accounts for people , websites files and stuff
