### ISSUE TITLE
Formats tooltip Bootstrap issue with cvana

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#280]
**Describe the bug**
There seems to be a clash between crouton and http://cvana.org, I'm thinking its the theme maybe, theres barely any plugins installed. This seems to be a bootstap clash with the tool tip. A quick google search yielded it a common problem.

**To Reproduce**
1. Go to cvana.org
2. Click on a format key
3. Click on another format key
4. the previous one doesn't go away.

**Expected behavior**
Tool tip closes

**Screenshots**
![Screen Shot 2020-09-10 at 9 21 31 PM](https://user-images.githubusercontent.com/34245618/92837476-a3b92b00-f3ab-11ea-8ccc-6e10e2890460.png)
![Screen Shot 2020-09-10 at 9 20 39 PM](https://user-images.githubusercontent.com/34245618/92837480-a451c180-f3ab-11ea-941b-c8318bfe92c9.png)

**Additional context**
Looks like Janice had same problem with Tabbed UI https://nameetinglist.org/forums/topic/jquery-issue/

**Comment by radius314** [comment]
Connecticut reported a similar issue a while back.

**Comment by otrok7** [comment]
This is solved with 3.16.2
