### ISSUE TITLE
CSS conflict when show_map="1" and if you click to show the format button, the popover hasn't display the text well "light-grey color font".

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#281]
**Describe the bug**
CSS conflict when show_map="1" and if you click to show the format button, the popover hasn't display the text well "light-grey color font".
**To Reproduce**
1. Go to 'https://csr.naquebec.org/trouver-une-reunion/'
2. Scroll down to a 'meeting-data'
3. Click on 'the format button from a displayed meeting'

**Expected behavior**
![Annotation 2020-09-14 150859](https://user-images.githubusercontent.com/3509271/93127688-5a632700-f69c-11ea-89f3-f09143cbd7e5.png)

**Screenshots**
![Annotation 2020-09-14 144711](https://user-images.githubusercontent.com/3509271/93127433-e7f24700-f69b-11ea-9f2e-84a7d172e2b6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [Chrome]
 - Version [85.0.4183.102]

**Additional context**
I didn't check every browser

**Comment by radius314** [comment]
It looks like you are using some custom CSS, is that the case?  If so can you share that?

**Comment by Klodd65** [comment]
#bmlt-tabs .nav-tabs > li.active > a,#bmlt-tabs .nav-tabs > li.active > a:hover,#bmlt-tabs .nav-tabs > li.active > a:focus {
background-color: #005a87;
}
#bmlt-tabs .nav-tabs > li > a {
background-color: #01d2d6;
}
#bmlt-formats.btn-xs,#map-button.btn-xs {
background-color: #01d2d6;
}
#bmlt-tabs .rowHighlight {
    background-color: #db4865;
    color: #eee;
}
#bmlt.tabs.table #nav-days.bmlt-tabs.show #ul.nac.nav-tabs{
background-color:#005a87;
}
#bmlt-tabs tr.meeting-header td {
background-color: #005a87;
}
#bmlt-tabs #day {
background-color: #005a87;
}
#bmlt-tabs #city {
background-color: #01d2d6;
}
#bmlt-tabs #day.btn.btn-primary.btn-sm.buttonHighlight {
background-color: #01d2d6;
}
#bmlt-tabs #day.btn.btn-primary.btn-sm.buttonLowlight {
background-color: #005a87; color: #fff;
}
#bmlt-tabs #city.btn.btn-primary.btn-sm.buttonHighlight {
background-color: #01d2d6;
}
#bmlt-tabs #city.btn.btn-primary.btn-sm.buttonLowlight {
background-color: #005a87;color: #fff;
}
#bmlt-tabs #bmlt-header #tabs-content {
background-color:#005a87;
}
#bmlt-tabs .filterButton.btn.btn-primary.btn-sm.buttonLowlight {
    background-color: #005a87;color: #fff;
}
#bmlt-tabs .filterButton.btn.btn-primary.btn-sm.buttonHighlight {
    background-color: #01d2d6;
}
#bmlt-tabs .bmlt-page {
    background-color: #005a87;
}
#bmlt-tabs .bmlt-header {
    background-color: #005a87;
}

**Comment by radius314** [comment]
There is a new theme in crouton 3.11.6 called "quebec" that is what you submitted here plus one minor fix for the issue you reported.
