### ISSUE TITLE
PL translation

### ISSUE THREAD

**Issue by arktys** [bmlt-enabled/crouton#283]
https://github.com/bmlt-enabled/crouton/blob/fd2ab03a3ee4c985e5ed4a4b64b34ddf258f37fc/croutonjs/src/js/crouton-localization.js#L239-L244 

"neighborhood": "Sąsiedztwo",
			"near_me": "Blisko Mnie",
			"text_search": "Wpisz",
			"click_search": "Kliknij na mapie",
			"pan_and_zoom": "Przesuń powiększ",
			"languages": "Języki",

**Comment by radius314** [comment]
thank you will be in crouton 3.11.6

**Comment by radius314** [comment]
actually will be 3.11.5
