### ISSUE TITLE
Query not returning full results

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#285]
I have an odd thing happening. When I go to search for meetings in Houston using the texasoklahomana.org server I'm not seeing all of the results. It stops on mid Thursday on some and mid-Saturday but they some off. I've tried it on all of the sites I manage and they are all the same. I'm on version 3.11.5 If I go to the semantic interface it pulls that information correctly along with the hascona.org website. I don't know what version of crouton they are on. These are the sites, https://nafreedom.org https://hillcountryna.org https://mrscna.net

**Comment by radius314** [comment]
By default, the first 50 closest meetings are returned from the location entered.  Is this still an issue?  If so which ones?

**Comment by radius314** [comment]
What's up with this?  Still happening?
