### ISSUE TITLE
Meetings before current time not being displayed for today in Version 3.11.6

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/crouton#289]
**Describe the bug**

Crouton is not displaying meetings in today's tab when the start time of the meeting has passed.

This is happening on every page that uses crouton in the na-ireland website. Here is one example

i.e. There is a 7.45 am meeting every day in Dublin, Ireland. It should be displayed in every day's tab in Crouton. It is currently not shown for todays tab.

https://www.na-ireland.org/na-meetings/east/dublin/

Similarly, none of today's meetings that have already started are being displayed. ie. the 11am meeting, the 7pm meetings etc (current time here in 7.20 pm)

The shortcode being used is

[bmlt_tabs custom_query="&amp;meeting_key=location_sub_province&amp;meeting_key_value=Dublin"]

I also see this on a page that uses the shortcode
[bmlt_tabs service_body_parent="1" has_zip_codes='0'  has_sub_province='1']

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the shortcode [bmlt_tabs custom_query="&amp;meeting_key=location_sub_province&amp;meeting_key_value=Dublin"] to a page
2. Display the page
3. Look at today's tab
4. Notice that none of the meetings for today, that start before the current time are being displayed

**Expected behaviour**
All the meetings for today should be displayed

**Screenshots**
Visit https://www.na-ireland.org/na-meetings/east/dublin/ 

**Desktop (please complete the following information):**
 - chrome, also evident on Firefox

No javascript errors in the browser

**Comment by jbraswell** [comment]
@paulnagle I am releasing 3.11.7 right now. When it's available, please upgrade, let us know how it goes.

**Comment by paulnagle** [comment]
Thanks @jbraswell The issue is resolved in 3.11.7
