### ISSUE TITLE
about us map codes

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#295]
looking at us map, when i click in a state, it opens a map with tabs meetings.... I know you did this code with croutonjs... how to have the same functionality with wordpress?

**Comment by radius314** [comment]
Yes, it is possible with crouton on WordPress.  You can pass query string parameters to Crouton that match shortcode values that will override or supersede what's in the shortcode.  The equivalent shortcode would be (you may have to change some of these parameters for your root server):

```
[bmlt_tabs custom_query=&services=-490&recursive=1&meeting_key=location_province&meeting_key_value=NY"]
```

You can then pass this as querystring parameter and change it accordingly:

https://example.org/page?custom_query=%26services%3D-490%26recursive%3D1%26meeting_key%3Dlocation_province%26meeting_key_value%3DNY

It's helpful to use the semantic workshop to explore what the right base query is you want: https://csa-saopaulo.org/bmlt/main_server/semantic
