### ISSUE TITLE
Weekday text stacking in Crouton on mobile phone

### ISSUE THREAD

**Issue by prbrian** [bmlt-enabled/crouton#296]
**Describe the bug**
The weekdays aren't displayed correctly on mobile phones. The font is cut off and stacked over top of itself.

**To Reproduce**
1. Using your mobile phone, go to 'www.niagarana.com'
2. See error in the crouton plugin

**Expected behavior**
The weekdays shouldn't be cut off and stacked. They should be in a continuous line.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.7
 - Browser: Safari

Screenshot attached
![Crouton error](https://user-images.githubusercontent.com/73750928/97783409-f0301400-1b6d-11eb-9939-2429a7135333.png)

**Comment by klgrimley** [comment]
This is a CSS conflict caused by the bootstrap file used by the theme. If you add `@media (max-width: 767px) { #nav-days .nav-tabs { flex-direction: column; } #bmlt-tabs .nav-tabs>li { border 1px solid #ddd; } #bmlt-tabs .nav-tabs>li>a { border-radius: 0 !important; margin-right: 0 !important; } }` to the custom CSS area in the crouton plugin. The first part fixes the main display issue and the next two clean up the display.

**Comment by prbrian** [comment]
Thanks so much Kevin! I have another question if you don’t mind... I’m wondering if the BMLT is compatible with Google Sites? Do we have the ability to embed it in the site? Brian S.Public Relations RepresentativeFellowship Development TeamOntario Region & Manitoba Area of Narcotics AnonymousCell: 289-668-6974Toll-free: 1-888-811-3887Website: www.orscna.orgEmail: pr@orscna.org  From: Kevin GrimleySent: November 2, 2020 7:53 AMTo: bmlt-enabled/croutonCc: prbrian; AuthorSubject: Re: [bmlt-enabled/crouton] Weekday text stacking in Crouton on mobile phone (#296) This is a CSS conflict caused by the bootstrap file used by the theme. If you add @media (max-width: 767px) { #nav-days .nav-tabs { flex-direction: column; } #bmlt-tabs .nav-tabs>li { border 1px solid #ddd; } #bmlt-tabs .nav-tabs>li>a { border-radius: 0 !important; margin-right: 0 !important; } } to the custom CSS area in the crouton plugin. The first part fixes the main display issue and the next two clean up the display.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by klgrimley** [comment]
You'd need to use croutonjs I believe. @radius314 or @pjaudiomv can better explain how to implement it.

**Comment by pjaudiomv** [comment]
yes you can use the embed code ![Screen Shot 2020-11-03 at 8 08 33 AM](https://user-images.githubusercontent.com/34245618/97989678-e0ead980-1dac-11eb-8f02-ba052be8cc7d.png) widget thing and embed the JS code there

![Screen Shot 2020-11-03 at 8 08 41 AM](https://user-images.githubusercontent.com/34245618/97989677-dfb9ac80-1dac-11eb-97c5-c093db7eb323.png)

this is the code for example here  https://sites.google.com/view/testpatrick/home

```html
 <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@bmlt-enabled/croutonjs/crouton.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@bmlt-enabled/croutonjs/crouton.min.js"></script>
    <script type="text/javascript">
        var crouton = new Crouton({
            "root_server": "https://www.nerna.org/main_server",
            "service_body": [ 2 ],
        });
        crouton.render();
   </script>
<div id="bmlt-tabs"></div>
```

this is the short readme for croutonjs https://github.com/bmlt-enabled/crouton/tree/master/croutonjs

and a list of all the parameter settings here https://github.com/bmlt-enabled/crouton/blob/master/croutonjs/src/js/crouton-core.js#L15-L58

**Comment by radius314** [comment]
Still need help @prbrian ?

**Comment by prbrian** [comment]
This is resolved! Thank you! Brian S.Public Relations RepresentativeFellowship Development TeamOntario Region & Manitoba Area of Narcotics AnonymousCell: 289-668-6974Toll-free: 1-888-811-3887Website: www.orscna.orgEmail: pr@orscna.org  From: Danny GershmanSent: November 13, 2020 10:19 PMTo: bmlt-enabled/croutonCc: prbrian; MentionSubject: Re: [bmlt-enabled/crouton] Weekday text stacking in Crouton on mobile phone (#296) Still need help @prbrian ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by radius314** [comment]
Glad to hear!
