### ISSUE TITLE
Crouton sizing/layout on mobile device

### ISSUE THREAD

**Issue by prbrian** [bmlt-enabled/crouton#300]
Crouton doesn’t display information properly on mobile device. Screenshot attached.
![00917585-CC02-46D9-8683-99980B4A30E6](https://user-images.githubusercontent.com/73750928/99156375-68c6c280-268e-11eb-9a38-d1b85b11ebce.png)

**Comment by radius314** [comment]
The screenshot seems to be cut off.  What version are you on?  Is this related to #296 ?

**Comment by prbrian** [comment]
Its not cut off. That’s how it’s displayed. I can’t scroll down anymore. And no it seems to be unrelated.

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: pr@orscna.org
Website: www.orscna.org

**Comment by radius314** [comment]
On this page?  https://niagarana.com

**Comment by prbrian** [comment]
No. I’m working on our Regional site

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: pr@orscna.org
Website: www.orscna.org

**Comment by radius314** [comment]
Do you have a link?

**Comment by prbrian** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by radius314** [comment]
This appears to be an iframe issue on Google Sites.  Not one related to
crouton.

**Comment by radius314** [comment]
I'm not sure how to get around this.  Google Sites (and other ones like
this use iframes for these types of HTML + Javascript embeds).  You can see
a scrollbar that would allow you to scroll down in the content frame.

Not sure what can be done here.

**Comment by prbrian** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by radius314** [comment]
[image: image.png]

**Comment by radius314** [comment]
Sample of me scrolling down on the mobile view on your Google Site.

![Screen Shot 2020-11-14 at 7 42 00 PM](https://user-images.githubusercontent.com/1850811/99160109-a1c45e80-26b1-11eb-8d1f-c82aa6242b16.png)

**Comment by prbrian** [comment]
Ok maybe it’ll be fine then.. fingers crossed. We’re gonna publish it soon Brian S.Public Relations RepresentativeFellowship Development TeamOntario Region & Manitoba Area of Narcotics AnonymousCell: 289-668-6974Toll-free: 1-888-811-3887Website: www.orscna.orgEmail: pr@orscna.org  From: Danny GershmanSent: November 14, 2020 7:43 PMTo: bmlt-enabled/croutonCc: prbrian; AuthorSubject: Re: [bmlt-enabled/crouton] Crouton sizing/layout on mobile device (#300) Sample of me scrolling down on the mobile view on your Google Site.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
