### ISSUE TITLE
When clicking on weekday tabs in Crouton, nothing happens

### ISSUE THREAD

**Issue by prbrian** [bmlt-enabled/crouton#301]
**Describe the bug**
If you click on the tab for say Monday, then click on a different day, nothing happens. 

**To Reproduce**
1. Go to 'www.niagarana.com'
2. Scroll down to the crouton plugin
4. Try clicking on a five or six different weekdays; see error.

**Expected behavior**
The meetings for each day of the week should appear as you click on each weekday tab.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android and Apple
 - Browsers: Chrome and Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by radius314** [comment]
Able to repro. Weird.

**Comment by radius314** [comment]
can you send me your shortcode?

**Comment by radius314** [comment]
I was able to grab the rendering and this is what it looks like off WP https://codepen.io/radius314/full/NWrJGmq

**Comment by prbrian** [comment]
So its a Wordpress issue?

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: pr@orscna.org
Website: www.orscna.org

**Comment by prbrian** [comment]
[bmlt_tabs] [bmlt_tabs has_cities='1' has_groups='0' has_areas='0' has_locations='0' has_sub_province='0' has_states='0' has_zip_codes='0' has_formats='1' has_neighborhoods='0'] Brian S.Public Relations RepresentativeFellowship Development TeamOntario Region & Manitoba Area of Narcotics AnonymousCell: 289-668-6974Toll-free: 1-888-811-3887Website: www.orscna.orgEmail: pr@orscna.org  From: Danny GershmanSent: November 15, 2020 9:20 PMTo: bmlt-enabled/croutonCc: prbrian; AuthorSubject: Re: [bmlt-enabled/crouton] When clicking on weekday tabs in Crouton, nothing happens (#301) can you send me your shortcode?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by radius314** [comment]
Do you have bmlt tabs mentioned twice there?  Your email client is
injecting some CSS here.

**Comment by prbrian** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by radius314** [comment]
It's really difficult to see what you are saying, can you post your response directly in GitHub.  Your email client is mangling your response.

**Comment by prbrian** [comment]
Sorry. To your email about injecting CSS I said... 
I’m not sure what that means ☹ sorry I’m not really a web guy

**Comment by radius314** [comment]
It looks better now that you are posting directly.  Can you re-post the short code that you are using?

**Comment by prbrian** [comment]
[bmlt_tabs] [bmlt_tabs has_cities='1' has_groups='0' has_areas='0' has_locations='0' has_sub_province='0' has_states='0' has_zip_codes='0' has_formats='1' has_neighborhoods='0']

**Comment by radius314** [comment]
ok it looks like you are doubling up here.

can you replace that with just the 2nd one?

```
[bmlt_tabs has_cities='1' has_groups='0' has_areas='0' has_locations='0' has_sub_province='0' has_states='0' has_zip_codes='0' has_formats='1' has_neighborhoods='0']
```

**Comment by prbrian** [comment]
I replaced it and the issue persists

**Comment by radius314** [comment]
Cannot repro locally.  What theme + plugins are you using?

**Comment by prbrian** [comment]
I believe the theme is OnePress and these plugins:
Bread
Crouton
Google Analytics for WordPress by MonsterInsights
WPForms Lite

**Comment by radius314** [comment]
Able to repro, the culprit is the theme "OnePress".  Digging into the root cause now.

**Comment by radius314** [comment]
I have spent about 2 hours on this and I'm no further.  There is some kind of conflict going on with this theme and crouton.  I'm going to stop looking and offer up that you use a different theme or if someone else might be able to better figure of what's going on here to take a look.

**Comment by prbrian** [comment]
Thanks for all your time spent on this Danny. Much appreciated.
