### ISSUE TITLE
Unable to close meeting formats list popup window

### ISSUE THREAD

**Issue by Connected57** [bmlt-enabled/crouton#314]
**Describe the bug**
Unable to close the popup window that displays the list of meeting formats that are associated with that particular meeting.

**To Reproduce**
1. Go to 'https://www.gcana.org/online-meetings/'
2. Scroll down to 'To any meeting within the Local Meeting's Tabbed UI'
3. Click on 'the meeting formats list icon (magnifying glass)'

**Expected behavior**
After clicking on the magnifying glass icon and seeing the list of meeting formats in the pop up window I expected it close when I clicked on the icon again or clicked somewhere else on the page. The only way to close the popup window(s) is to refresh the page.

**Screenshots**
![Meeting_Format_Popup_Window_Bug](https://user-images.githubusercontent.com/5223400/101517648-d389b780-3935-11eb-956f-0924626af9be.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - Browser Chrome
 - Version 87.0.4280.88

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android version 11
 - Browser Chrome
 - Version 87.0.4280.86

**Additional context**

**Comment by otrok7** [comment]
This is solved with 3.16.2
