### ISSUE TITLE
better way to say there aren't any meetings yet in the database

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/crouton#318]
When new areas come on to a BMLT server, and point to the new service body, crouton gives a scary-looking error message, like this one that we just saw come through on the help email:

`Could not find any meetings for the criteria specified with the query https://canaacna.org/meetings/main_server/client_interface/jsonp/?switcher=GetSearchResults&get_used_formats&lang_enum=en&data_field_key=location_postal_code_1,duration_time,start_time,time_zone,weekday_tinyint,service_body_bigint,longitude,latitude,location_province,location_municipality,location_street,location_info,location_text,location_neighborhood,formats,format_shared_id_list,comments,meeting_name,location_sub_province,worldid_mixed,root_server_uri,id_bigint,meeting_name,location_text,formatted_address,formatted_location_info,virtual_meeting_additional_info,virtual_meeting_additional_info,virtual_meeting_link,virtual_meeting_link,show_qrcode,virtual_meeting_link,phone_meeting_number,phone_meeting_number,show_qrcode,phone_meeting_number,latitude,longitude,latitude,longitude,map_word,latitude,longitude,contact_name_1,contact_phone_1,contact_email_1,contact_name_2,contact_phone_2,contact_email_2&services[]=30&recursive=1&sort_keys=start_time`

It seems better to have something clearer and less scary looking, for example:

`No meetings saved in the database yet for this service body!`

**Comment by radius314** [comment]
The messaging you are proposing is not completely accurate.  There may be meetings for a given service body, but other parameters in a custom query could cause it to return 0 meetings.

**Comment by alanborning** [comment]
Well, that's true. But the current error message is both accurate and a usability disaster. Do we need to display all that stuff? If not, how about:

`No meetings found. (Perhaps there aren't any meetings yet in the database for this service body?)`

or if we really need to talk about queries (which is going to scare some people), how about:

`No meetings found for this query. (Perhaps there aren't any meetings yet in the database for this service body?)`

Or if this still leaves out essential information, what would be a message that would be both accurate and usable?

**Comment by radius314** [comment]
My belief is that this message was for administrators, would occur while setting things up, not for an end user.  Who is the audience?

**Comment by EddieW1** [comment]
With many meetings either gone or closed due to Covid it would seem that the regular Crouton interface with no listed meetings would be a better option than this error message.

We have the same issue with a couple of locations in our Region and have just replaced the short code with the text there are no meeting at this time until a better option presents itself.

Personal preference would be the Crouton Block with all days empty.

**Comment by alanb2718** [comment]
Resurfacing this issue in the hope that we can agree on a solution.  This continues to be a problem when I'm helping new regions and areas get onto BMLT -- the first thing they see when they try to get a meeting list set up so that they can monitor their progress is this alarming error message.  I usually add one meeting myself just so they don't see it and get scared off.

Very simple solution: how about changing the message to "No meetings found"?

**Comment by radius314** [comment]
I would feel more comfortable with doing that if we could combine both
together.  It’s not sufficient for the person who is actually going to deal
with the error to go off that message.

What I would propose is to show in some large font the message you propose,
and then to output to the JavaScript console (or in HTML in a expandable
initially hidden div/span) what is currently displayed.

—Danny

**Comment by alanb2718** [comment]
Well, I'm not convinced we need that -- if I saw a message "No meetings found" I'd just start poking around to find out why, and uncover the problem that way.  But if you think it's needed, I'd go along with the solution you propose, since it would solve the scary warning problem.

**Comment by radius314** [comment]
![image](https://user-images.githubusercontent.com/1850811/127932216-22da032b-d1a5-4855-97fc-e061dd17b0b2.png)

in MR: https://github.com/bmlt-enabled/crouton/pull/341
