### ISSUE TITLE
Urgent - Crouton completely stopped working - no list no table

### ISSUE THREAD

**Issue by mascnawebservant** [bmlt-enabled/crouton#319]
Hi. I am not sure when this started but it was reported yesterday.

https://mascna.org/wp/meetings/

Fetching briefly flashes but nothing is rendered. I've reset defaults, removed the module and re-installed (newbie thinking WP is like WIndows?)

Using this shortcode and have tried variations/minimal:
[bmlt_tabs header="1" show_distance="1" has_zip_codes="0" distance_units="km" service_body="52"]

I am not sure what has caused this; haven't made any recent changes. Maybe WP auto-updates.

This brings to light a real recovery concern for meeting lists vs. the old way. BMLT app seems to work fortunately.

Thanks for any help!

**Comment by radius314** [comment]
Not sure what's going on.  Might be a theme conflict.

**Comment by mascnawebservant** [comment]
Thanks. Theme hasn't changed though there were version updates. Rolled back to months ago and still not working. I will try the code with blank WP theme maybe.

**Comment by radius314** [comment]
You could also try to do

`[init_crouton header="1" show_distance="1" has_zip_codes="0" distance_units="km" service_body="52"]` and then

`[bmlt_tabs]`

**Comment by mascnawebservant** [comment]
Thanks for the quick help Danny. Yes it appears to be a theme issue indeed. I've been using a builder called Themify. It's been working all this time but yeah now something is going on because when I stop using it and go back to OOB WP I can see meeting data. Uggggh. I'll check with their support I guess. Odd because I rolled back to version from months ago and it also isn't working.

**Comment by mascnawebservant** [comment]
Yup def related to using Themify. Workaround issued. Closing. Thanks again!
