### ISSUE TITLE
How to show near meetings first using bmlt_tabs shortecode

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#320]
What shortecode can we use to show first the nearest meetings ....
this is our code in use now:

[crouton_map map_search_width="-20" map_search_auto="true" show_distance="1" map_search_zoom="6" time_format="HH:mm" distance_units="km" language="pt-BR" int_start_day_id="1" view_by="location_municipality" has_cities="0" has_groups="0" has_areas="0" has_locations="0" has_sub_province="0" has_states="0" has_zip_codes="0" has_formats="0" has_weekdays="0" has_neighborhoods="0"]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by radius314** [comment]
Did you still need help with this?
