### ISSUE TITLE
why shortecode [group_count service_body="2"] do not show only groups from service body ID=2

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#321]
Hello guys,

We trying to show seletive group and meetings count from some of service bodies using shortecode:

CSR Brasil: Com [group_count service_body="2" header="0" has_tabs="0"] grupos com [meeting_count service_body "2" header="0" has_tabs="0"] reuniões por semana.

Other question is: there´s a way to show open and close meetings count?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgershman** [comment]
include `recurse_service_bodies="1"`
