### ISSUE TITLE
Dutch language request

### ISSUE THREAD

**Issue by Hurmsss** [bmlt-enabled/crouton#324]
**Is your feature request related to a problem? Please describe.**
I don't see any Dutch options in this list: https://github.com/bmlt-enabled/crouton/blob/master/croutonjs/src/js/crouton-localization.js 

**Describe the solution you'd like**
So i would like to input the Dutch language

What steps should i take?

Big hugs, thank you
Hermen

**Comment by radius314** [comment]
Could you supply translations for the following words/terms on the right side of the colon?

```
"days_of_the_week" : ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
"weekday" : "Weekday",
"city" : "City",
"cities" : "Cities",
"groups" : "Groups",
"areas" : "Areas",
"locations" : "Locations",
"counties" : "Counties",
"states" : "States",
"postal_codes" : "Zips",
"formats" : "Formats",
"map" : "Map",
"neighborhood": "Neighborhood",
"near_me": "Near Me",
"text_search": "Text Search",
"click_search": "Click Search",
"pan_and_zoom": "Pan + Zoom",
"languages": "Languages",
```

**Comment by Hurmsss** [comment]
Allright, thank you! Here is the information

"days_of_the_week" : ["", "Zondag", "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag"],
"weekday" : "Dag van de week",
"city" : "Stad",
"cities" : "Steden",
"groups" : "Groepen",
"areas" : "Gebieden",
"locations" : "Locaties",
"counties" : "Landen",
"states" : "Provincies",
"postal_codes" : "Postcodes",
"formats" : "Formats",
"map" : "Kaart",
"neighborhood": "Buurt",
"near_me": "Bij mij in de buurt",
"text_search": "Zoek op tekst",
"click_search": "Klik om te zoeken",
"pan_and_zoom": "Pan + Zoom",
"languages": "Talen",

**Comment by radius314** [comment]
What country is this for?

**Comment by Hurmsss** [comment]
The Netherlands

Verstuurd vanaf mijn iPhone

**Comment by Hurmsss** [comment]
Thank you for the help Radius314. If there is anything more i can do to help, please let me know.

**Comment by Hurmsss** [comment]
Can you maybe explain to me how i can get the meetingschedule now in dutch on my webpage? When i use this: [bmlt_tabs language="nl-NL"] it do longer show anything on my page.

**Comment by pjaudiomv** [comment]
> Can you maybe explain to me how i can get the meetingschedule now in dutch on my webpage? When i use this: [bmlt_tabs language="nl-NL"] it do longer show anything on my page.

it has not been released to wordpress yet, if you wanted to test it you could use this zip here https://archives.bmlt.app/crouton/crouton-build825-659d3c22d336e24bed3b12177cdbad09701d8ff3.zip

**Comment by Hurmsss** [comment]
Allright, so it will be there in the next update? Thanks for responding!

**Comment by radius314** [comment]
3.11.15 was released which supports this.
