### ISSUE TITLE
404 - crouton plugin documentation link

### ISSUE THREAD

**Issue by rogersearle** [bmlt-enabled/crouton#330]
Crouton plugin settings > Google API Key section: has a "For more information" link [https://bmlt.app/google-maps-api-keys-and-geolocation-issues/](url) that is a 404

<img width="246" alt="Screen Shot 2021-04-21 at 5 02 21 AM" src="https://user-images.githubusercontent.com/55562001/115436467-2453da00-a25f-11eb-8c7b-1e8122b87a71.png">

Shoud be [https://bmlt.app/google-api-key/](url)

**Comment by radius314** [comment]
will be in the next release

**Comment by radius314** [comment]
will be available in 3.12.0, released shortly
