### ISSUE TITLE
Formats error

### ISSUE THREAD

**Issue by Hurmsss** [bmlt-enabled/crouton#331]
**Describe the bug**
When i click on the little formats button, it does not show a desciption:
![image](https://user-images.githubusercontent.com/82229149/115863876-62572680-a436-11eb-837b-2b38eab227f2.png)

**Expected behavior**
I expect to see a description of the different formats, and what kind of format this meeting is. 

**Screenshots**

**Desktop (please complete the following information):**
Windows computer, webpage on Chrome and Edge

Anyone knows what i might be doing wrong? 
Kind regards,
Hermen

**Comment by pjaudiomv** [comment]
Can you link to the website this is being used on, also are you on latest version.

**Comment by Hurmsss** [comment]
I am using it on www.nahelp.nl
Have to check what version I am on when I get home. 

Verstuurd vanaf mijn iPhone

**Comment by tempsaint** [comment]
The is the same thing that's happening on ctna.org. We think it's a jquery issue but we were never able to solve it.

**Comment by Hurmsss** [comment]
Owke, so there is not much i can do to change it. 

Is there a way to delete the button then and the formats tab, and just put it in as text in every meeting seperate?

**Comment by pjaudiomv** [comment]
I think this is actually a result of not having a Dutch translation or formats for the root server

**Comment by pjaudiomv** [comment]
I could be wrong, but i think this may be the reason

**Comment by pjaudiomv** [comment]
![Screen Shot 2021-04-23 at 12 03 19 PM](https://user-images.githubusercontent.com/34245618/115898799-f374d000-a42b-11eb-8db1-0f19293feca1.png)

yes the one call is specifying `lang_enum=en` and the other `lang_enum=nl` which doesnt exist

**Comment by alanb2718** [comment]
To address this, I'm assuming the way to proceed is to give the Dutch folks the `InitialFormatsData-en.sql` file that has the English version of the initial formats, have them translate everything, then add the new file `InitialFormatsData-nl.sql` that is the Dutch version to the initial install and also to their current server. Does that seem right?

**Comment by pjaudiomv** [comment]
yea may not hurt to see if they want to do a proper translation of UI too. im curious why one is using en and other nl though.

**Comment by Hurmsss** [comment]
Sounds good, i am not a programmer so i would love some simple step by step explanations if that is possible

**Comment by Hurmsss** [comment]
I made my own formats by the way, not sure if that is a problem. I added them on the root server i installed.

**Comment by alanb2718** [comment]
We can help with explanations etc -- this shouldn't be too hard to do.  There will be a certain amount of back-and-forth however, I'd rather use email or slack rather than putting it in this issue on github.  (Plus it is no longer about crouton actually, but the root server.) Could you send me an email at alan@bmlt.app, and in the email let me know the URL for your root server?

**Comment by radius314** [comment]
I'm guessing this isn't a bug, can we close it?
