### ISSUE TITLE
Formats not opening

### ISSUE THREAD

**Issue by Hurmsss** [bmlt-enabled/crouton#336]
**Describe the bug**
When i go to the webpage and th emeetinglist. It does not show the description of the formats. 

**To Reproduce**
1. Go to 'the meetinglist on [nahelp](https://nahelp.nl/na-meetings-nederland/)

**Expected behavior**
I wish to see it opening and showing what the descriptions are (BT) should show Basic Text for example. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82229149/124360668-57392780-dc2b-11eb-9d66-712413b75aac.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone]

**Additional context**
Anyone knows what i can do to fix this?

Kind regards

**Comment by pjaudiomv** [comment]
What version of the plug-in are you using and can you please post a link to the site it's happening on

**Comment by Hurmsss** [comment]
I use version 3.12.1 crouton

And it is on the website www.nahelp.nl [https://nahelp.nl/na-meetings-nederland/](url)

**Comment by pjaudiomv** [comment]
Oh I see you opened the same issue before here https://github.com/bmlt-enabled/crouton/issues/331  Did you ever talk to @alanb2718  about this

**Comment by Hurmsss** [comment]
No not yet. 
Ow yes i see he asked me to send him an email, i will do that! Sorry

**Comment by alanb2718** [comment]
I will follow up by email with @Hurmsss .... will close this issue, since it's actually a root server question (need to add support for Dutch).
