### ISSUE TITLE
Hide "Facility is Temporarily Closed" ?

### ISSUE THREAD

**Issue by mascnawebservant** [bmlt-enabled/crouton#337]
Hi. How are you guys handling cases where groups still have some virtual meetings and some in person which sometimes overlap and sometimes don't. The message "Facility is Temporarily Closed" for virtual meetings is confusing when the facility isn't actually closed.

Any suggestions appreciated.

**Comment by alanb2718** [comment]
My suggestion is to mark these as "Hybrid", and in the Comment field (under the "Other" tab on the meeting editor) put an explanation of exactly how the meeting is running.  If you want, you could change the description for the Hybrid format to be more inclusive -- but the advantage of using it is that it has places for information about both a physical location and a virtual meeting.  

For example, there is a meeting in my area that meets outside if the weather is good, and on zoom if it's raining.

**Comment by mascnawebservant** [comment]
Hi. Thanks. The thing is though some of the meetings they have in person
AND zoom at the same time. I will play around with settings. The best
solution might be if devs could add a checkmark for show facility closed
message.

**Comment by jbraswell** [comment]
If there is an in-person and a separate zoom meeting at the same time, it is best to list it as two separate meetings, and mark one as in-person and the other as virtual. After all, they really are two separate meetings.

The "facility is temporarily closed" message won't show up if the correct venue type is selected for the meeting.

Check out this blog post: https://bmlt.app/root-server-release-2-16-0/

It says:

> There might be a group that has decided to divide into two separate meetings, one in person and the other virtual, still meeting at the same time. One approach here is to duplicate the listing and have two meetings, one in person and one virtual. Alternately, if the group or webservant wants to avoid having two separate listings, mark this as a Hybrid meeting, and explain the particular way the meeting is run in the Comments field. Or there might be some other variation, for example, starting out as one meeting, and then splitting into two after the opening readings — explain this in the Comments field as well.

**Comment by radius314** [comment]
You could also do in CSS

```css
.temporarilyClosed { display: none; }
```
