### ISSUE TITLE
Italian language not working due missing translated word.

### ISSUE THREAD

**Issue by Rizoma83** [bmlt-enabled/crouton#351]
Italian language not working

if i use [bmlt_tabs language="it-IT"] shortcode it will output js error because "share" word is missing from italian translation.

how to solve:
modify this file
/wp-content/plugins/crouton/croutonjs/dist/crouton.nojquery.min.js
this string
{IN_PERSON:"In Person",VIRTUAL:"Virtual"}},"nl-NL":
should become
{IN_PERSON:"Di persona",VIRTUAL:"Virtuale"},share: "condividi"},"nl-NL":

**Comment by dgershman** [comment]
will be in 3.12.4
