### ISSUE TITLE
Extra Padding For Cities Popup (Responsive)

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/crouton#370]
When viewed on a small screen, the popovers rearrange, but the Cities popup has extra padding in front (see attached).

I am using an iPhone Mini (12), using Safari.

The URL is https://heartoflongislandna.org/meetings/

![IMG_3772](https://user-images.githubusercontent.com/51290189/152520925-903c8269-3fbc-4a6c-af82-ecac33b5fa71.jpeg)

**Comment by dgershman** [comment]
This is a theme issue.  Here is the same with the default
https://heartoflongislandna.org/meetings/?theme=jack.

**Comment by dgershman** [comment]
Don’t close it.  We will fix it.

**Comment by dgershman** [comment]
released in 3.13.0
