### ISSUE TITLE
Remove/Hide "Pan + Zoom" option in crouton_map

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/crouton#373]
I am suggesting that the Pan + Zoom option which is displayed at the bottom of the search options (and selected by default) in the crouton_map be removed or hidden. I believe the perception is that the search results will update AS you pan + zoom, but they don't. I understand the need to move the map so that you might be able to "click search" elsewhere, or a need to zoom in/out (which you are able to do already with the +/- buttons in the lower right of the map) but, again, the Pan + Zoom option gives a perception that search results will update as the user pans around.  This isn't accurate and causes confusion, I believe.

**Comment by dgershman** [comment]
I understand what you are saying, and I agree.  I need to think through the UI for it.

**Comment by dgershman** [comment]
This is pretty straightforward it turns out.

**Comment by dgershman** [comment]
released in 3.13.0
