### ISSUE TITLE
Make "Near Me" the default behavior for crouton_map

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/crouton#374]
I am asking that the `map_search_auto="true"` be the default behavior for the base `crouton_map` shortcode option. Currently the base shortcode does nothing but display the middle of a body of water. Nothing happens and you can just stare at that blue all day without even knowing you're looking at a map. By making it auto search by default, end users will automatically be shown the closest 50 meetings to their location (barring any other parameters being added to the shortcode).  Webservants would still be able to override this by adding `map_search_auto="false"` to the shortcode if they want.

**Comment by dgershman** [comment]
will be in 3.13.0

**Comment by tempsaint** [comment]
Need to update this in the plugin documentation: 

`[crouton_map map_search_auto="true"] - specifies if you want to automatically use your current latitude and longitude to find meetings (default: false).`
