### ISSUE TITLE
Open-Ended Meetings Display an End Time

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/crouton#385]
**Describe the bug**
Well, I'm not sure if this is actually a "bug" per se, since I believe crouton is behaving exactly as expected, but, meetings that are marked in the root-server as open-ended are appearing with an end time that can be confusing for website viewers. 

Apparently, if a meeting duration is selected (in a root server) as `open-ended`, the root server stores that value as `24:00:00`.  Crouton, naturally, then displays the start time and end time of the meeting as what appear to be the same value (ie. 8:00pm - 8:00pm), giving the appearance that the meeting is 0 minutes in duration. It's actually displaying that the meeting is 24 hours in duration, however there's no indication that the end time is the next day. 

**Expected behavior**
I recommend that crouton be reconfigured to not display an end time if the duration of a meeting is `24:00:00`.  So, for example, it would just state "8:00pm -  " (I think leaving the dash is good in that it provides a visual indicator that there's no end time). 

**Screenshots**
<img width="807" alt="image" src="https://user-images.githubusercontent.com/38324357/166562239-44040cd6-ab6e-484f-9bb3-bfb3eca0e8ab.png">

**Comment by dgershman** [comment]
This seems straightforward.  If the start time and end time are the same then to simple show the start time.

**Comment by pjaudiomv** [comment]
@tempsaint any chance you can test this release which should contain a fix https://s3.amazonaws.com/archives.bmlt.app/crouton/crouton-build1090-54c41770108467c58cfe58a07418f2c3b6af3a4a.zip

**Comment by tempsaint** [comment]
Well, it wasn't my site that had the issue, but I guess I can replicate and test.

**Comment by tempsaint** [comment]
Looks good

![image](https://user-images.githubusercontent.com/38324357/166570080-abfed3a8-e01a-4871-bbaa-6adc56b2cbaa.png)

**Comment by pjaudiomv** [comment]
Awesome 😎

**Comment by pjaudiomv** [comment]
resolved via https://github.com/bmlt-enabled/crouton/pull/386 and released in 3.14.0
