### ISSUE TITLE
fix google map api stuff

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#4]
remove any unused stuff and make sure what is being used is up to current API specs.

**Comment by radius314** [comment]
i temporarily disabled this, to remove the annoying location ask

**Comment by radius314** [comment]
should we close this, since we aren't gonna even use this?

**Comment by radius314** [comment]
maybe we should add a map feature

**Comment by pjaudiomv** [comment]
I would close it, though a map feature would be cool, like kml map with clickable markers. Which would require api key. You had mentioned this before when initially thinking of forking plugin and thought it was good idea.
