### ISSUE TITLE
Add to venue tab "Hybrid' meeting

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#408]
Is it possible to create a new feature about to add to venue tab this option Hybrid (in person and virtual) meeting ?
![Capture d’écran 2023-01-19 115859](https://user-images.githubusercontent.com/3509271/213510703-489d52a3-0157-494c-9709-e61d0a487cf4.png)

**Comment by otrok7** [comment]
Hybrid meetings are listed when filtering for virtual and for in-person meetings.   I think this is correct.  People that are looking for an in-person meeting probably don't care that it is also hybrid, and same for people looking for a virtual meeting.  Do you have a use-case in mind?
