### ISSUE TITLE
Format creation and showing on the webpage

### ISSUE THREAD

**Issue by HT1990ZWO** [bmlt-enabled/crouton#434]
When i try to add a new Format, it does not come through. I add the information but it just doesn't save. **Describe the bug**

**To Reproduce**
1. Go to '...' Create new format
2. Click on '....' i type in all the info.
3. Scroll down to '....' i click save
4. See error - it just keeps loading and nothing happens. 

I expected it to save a new format, wich i could use for adding meetings. 
**Expected behavior**

I work on windows laptop, and use browers Brave and Chrome. 
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pjaudiomv** [comment]
What server are you on

**Comment by otrok7** [comment]
Do you have any quote marks or apostrophes in your format description?

PS:  Crouton is the part of the toolbox that displays meeting information on webpages, it's not where formats or meeting info is entered.  That is the "Root Server".  Please consider moving this bug there.
