### ISSUE TITLE
TZ settings for Virtual NA sites not carrying across when displaying on remote site.

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/crouton#438]
**Describe the bug**
We are pulling in details from the Virtual-NA BMLT to a page on the Australian NA website using the following shortcode.

[bmlt_tabs root_server="https://bmlt.virtual-na.org/main_server" service_body="1,13,21" recurse_service_bodies="0" include_city_button="0" has_zip_codes="0" has_cities="0" has_locations="0" has_languages="1" has_areas="0" base_tz="UTC" filter_tabs="1" auto_tz_adjust="1" default_filter_dropdown="languages=english-speaking" metadata_template="{{formatLink this.formatted_comments}}"]

The page used to show meetings automatically adjusted for the viewer's timezone in the same way it does on Virtual-NA.org.

The page is listed here - https://www.na.org.au/multi/globally-published-australian-online-meetings/

A test page is listed here - https://brucegardner.net/myworld/test-page-for-virtual/

The key difference between these two pages is that the "Default template settings" were applied to the na.org.au site but not to the test page.

**To Reproduce**
1. Go to each page linked above and compare the meeting times 
2. Click on compare the meeting times for Sunday NA@Home lunchtime meetings.  Both are pulling from the same database but showing different times.

**Expected behavior**
We expect that the meeting times should autonatically adjust to the time of the viewer like on Virtual NA

**Screenshots**
Live site with problem
<img width="946" alt="image" src="https://github.com/bmlt-enabled/crouton/assets/29008815/184a3655-3438-40e4-a44f-f41eebc35761">

Test site showing correct times,
<img width="946" alt="image" src="https://github.com/bmlt-enabled/crouton/assets/29008815/f9cc15f1-2abc-4e9b-ad26-2db677a65544">

**Additional context**
Updated Crouton recently and applied the new Individual pages for meetings update.

**Comment by otrok7** [comment]
The configuration auto_tz_adjust is not set when the crouton table is being generated.  The configuration in the [bmlt_tabs] shortcode is being overwritten by the configuration in the [meeting_count] shortcode.  Setting auto_tz_adjust in the meeting_count shortcode seems to work, but I recommend just setting "has_meeting_count=1" in the [bmlt_tabs].  This is not only more efficient, in 3.17, the count will reflect the current filters, which is cool.

I have no explanation as to why this ever worked, the bug doesn't seem to be new.  I will investigate further, and try to make these multiple calls to crouton more stable.

**Comment by otrok7** [comment]
Oh, and this is probably related to the other problem, meeting-details that try to fetch the data from the wrong root server.  Either use "has_meeting_count=1" or set the "root_server" and the problem should go away.  Let me know.

**Comment by otrok7** [comment]
OK, now I get what is going on here.  You are calling meeting_count with a different root server, and this has a side effect of adding the meetings in the second shortcode to the meetings in the first shortcode.  Well, I see the use case but this solution is just crazy hacky... it pretty much is a text book for relying on side effects.  I'd like to provide a solution for this, but it will not be backwards compatible ... in other words, you'll have to change your page a bit.  Is that OK?

**Comment by otrok7** [comment]
Yes! Include has_meeting_count=1 in your bmlt_tabs shortcode.  This is better anyway, because it's more efficient and in 3.17 will be tied into the filters, so that filtering on the format "women's meeting" will give you the count of womens meetings.
