### ISSUE TITLE
URL parameter for show_map stopped working

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/crouton#441]
**Describe the bug**
The URL parameter for show_map has stopped working in crouton version 3.17.2.  It still works as a parameter for the short code though, and other URL parameters seem to be working OK.

**To Reproduce**
Go to this URL:  https://meetings.wszf.org/?show_map=1
This used to show a map, and now it hangs.

**Comment by otrok7** [comment]
We use this parameter to determine whether to load the map JS.  But we are not checking the query string.
