### ISSUE TITLE
Lack of throbber causes non-Wordpress sites to fail

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/crouton#457]
**Describe the bug**
It looks like non-Wordpress pages are having an issue when the throbber div is not present.  This causes crouton to not render.

**To Reproduce**
1. Create a crouton page not running in Wordpress (you can use this one for testing https://codepen.io/radius314/full/XWGNxRx)
2. Open Developer tools and notice the error present (sample error below).
```
crouton.js:17905 Uncaught TypeError: Cannot read properties of null (reading 'myThrobber')
    at showThrobber (crouton.js:17905:14)
    at loadAllMeetings (crouton.js:17925:5)
    at MeetingMap.loadFromCrouton [as initialize] (crouton.js:17840:3)
    at Crouton.self.renderStandaloneMap (crouton.js:16396:14)
    at Crouton.searchMap (crouton.js:16934:7)
    at new Crouton (crouton.js:16779:39)
    at XWGNxRx?nocache=true&view=fullpage:50:23
```

**Expected behavior**
No error should occur, also crouton should render.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Happens on all OSes

**Smartphone (please complete the following information):**
Happens on all OSes

**Additional context**
I would recommend that we check for the presence of the div and if it's not present fallback to continue.  You could potentially insert the `div` yourself, or if that is not desirable, include some kind of documentation to include that div.  I would prefer the prior option.  Temporarily I will work around this by creating the div myself.

**Comment by dgershman** [comment]
Upon further review, this issue seems to be deeper than I thought, the BMLT search modal seems to be a Wordpress only feature.  The more recent changes in crouton seems to have made croutonjs unusable.

**Comment by otrok7** [comment]
Settle down, I am really not so shitty.   I test croutonjs too, using ketchup as an example.  The problem with your test is that croutonjs assumes that the crouton object needs to be created in the body, after the point where the #bmlt-tabs ID is defined.  Or in a onReady().  This is not new.

**Comment by dgershman** [comment]
Apologies if I came off harsh. I thought maybe you might’ve thought it was something obvious. I can take a look and try to debug exactly what’s going on later on tonight

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by otrok7** [comment]
I did find a bug through when you do coordinate-searches in the stand-alone map outside of wordpress, so thanks for the bug report.  If you will be satisfied with requiring the script go after the bmlt-tabs <div>, I can get a bug fix out tonight.  Sorry if I came out snappy.  I was trying to figure out the bug and a bit distracted.  But I am committed that croutonjs work and we will definitely get there.

**Comment by dgershman** [comment]
You can use this to test.  https://codepen.io/radius314/pen/XWGNxRx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by otrok7** [comment]
Are you sure that exactly this code should work?  In particular, "template_path" is not defined, so the system doesn't know where to get things like the throbber and the meeting icons.  There is a bug there that I would like to fix, but not if the fix is incomplete.

**Comment by dgershman** [comment]
The issue is that the javascript block for starting crouton has to be after `</html>`.  It's working after I do that.

https://codepen.io/radius314/pen/gOwryJV
