### ISSUE TITLE
Meeting Details Popup Window

### ISSUE THREAD

**Issue by kaldoon** [bmlt-enabled/crouton#466]
**Describe the bug**
User sent to Virtual-NA

I don’t want to go back one screen, to the main site where I have to select “find a meeting” again and, wait for the meetings to be “fetched” and then scroll all the way down to the correct meeting. I simply want to close the window (which pops up when you click on the meeting title) and return to the where I was on the page before the window popped up. 

The buttons in the pop up window don’t work for me. I’m talking about the x in the top right corner of the popup window, not the browser window. 

**To Reproduce**
1. go to meetings
2. Click on 'meeting name'
4. The X and close button do not take one back to the meeting list 

**Expected behavior**
That the X and close button close the pop window and put one back on the meeting page 

**Screenshots**
![crouton240209](https://github.com/bmlt-enabled/crouton/assets/91600452/45c702dc-a020-4b1a-aa2f-1d6ea0adabe1)

![kw02092024user](https://github.com/bmlt-enabled/crouton/assets/91600452/4485b450-ebfc-4e0f-b83b-a1957e360451)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by otrok7** [comment]
This bug was fixed back in December.  It seems you are not using the latest version of the code.  Please update.

**Comment by otrok7** [comment]
Fixed after update
