### ISSUE TITLE
Fetching

### ISSUE THREAD

**Issue by kachrisman** [bmlt-enabled/crouton#470]
**Describe the bug**
On mobile: bmlt meeting tabs via crouton showing "fetching". Not seeing it on Desktop. Cache was flushed and settings reviewed. Appears to be happening only on Safari. 

**To Reproduce**
1. Go to ['...'](https://midmissourina.com/find-a-meeting/)
3. Scroll down to '....' Find An In-Person Or Zoom Meeting

**Expected behavior**
Should display bmlt meetings tabs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]MAC Sonoma 14.0 (23A344)
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]Version 120.0.6099.129

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Plus
 - OS: [e.g. iOS8.1] iOS 17.2.1
 - Browser [e.g. stock browser, safari]Safari
 - Version [e.g. 22]17.2.1

**Additional context**

**Comment by otrok7** [comment]
Hello.  I suspect this has something to do with the way your optimizer (autooptimize) is working.  Can you try to disable it on this page?

**Comment by kachrisman** [comment]
> Hello. I suspect this has something to do with the way your optimizer (autooptimize) is working. Can you try to disable it on this page?

That was the issue. Thanks for your help

**Comment by otrok7** [comment]
I notice that there seems to be a problem with your Google maps API key.  If you can't generate a new one, you can go to Settings->crouton->Maps and select "Open Street Maps" instead of Google.  It's much faster, anyway.
