### ISSUE TITLE
Location gathering twice with map and show_distance on firefox

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#480]
**Describe the bug**
When loading crouton with map search and show_distance it prompts your browser for location twice, once for meeting search and again for distance from your browser location. I also swear i hit this under another scenario but cant remember what.

**To Reproduce**
1. Go to [https://ketchupsearch.org/](https://ketchupsearch.org/)

**Expected behavior**
User is prompted once for location

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Mac OS 14.5]
 - Browser [ Firefox ]
 - Version [126.0.1]

**Additional context**
This happens with firefox and safari for me but not chrome. I'm guessing has to do with privacy settings.

**Comment by otrok7** [comment]
Closed 3.19.2
