### ISSUE TITLE
Weird rendering issue iPhone

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/crouton#482]
**Describe the bug**
When I run a search on crouton, I get the below screenshot. The close X seems to be off and also the buttons don't seem to be equally spaced.

**To Reproduce**
1. Go to 'crouton' on any site and click Search for Meetings.  Observe the modal.

**Expected behavior**
That the close button would be aligned correctly and not overlapping.  And also the buttons would be equally spaced.  Also the "Search for Meetings".  

**Screenshots**
![image](https://github.com/bmlt-enabled/crouton/assets/1850811/31cc29f7-f61c-49f5-8a9f-d7a996255906)

**Desktop (please complete the following information):**
 - OS: ios17
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by otrok7** [comment]
Yeah, that whole dialog is pretty ugly.  I've tried to clean it up a bit, but I'm not a very competent UI designer.  Can you try the beta (https://github.com/bmlt-enabled/crouton/releases/tag/3.19.2-beta1) and let me know if it's OK, and if you have any suggestions.
