### ISSUE TITLE
Link to google maps should open in new tab

### ISSUE THREAD

**Issue by GarrettWeinberg** [bmlt-enabled/crouton#483]
**Is your feature request related to a problem? Please describe.**
when looking at the meeting details modal, the link for google maps opens in the same tab.

**Describe the solution you'd like**
add target="_blank" to any place that is opening an external site

**Describe alternatives you've considered**
Tried adding a javascript snippet to our theme js file, but this modal is loaded after the DOM so this fix doesnt work. 

**Additional context**

**Comment by otrok7** [comment]
The correct place to fix this is in the crouton settings, on the "Templates" tab.  But in recent versions, target=_blank is already set.  So you might try just setting the template to the default.  Templates don't update automatically... I'm afraid to overwrite customizations.
