### ISSUE TITLE
"Fetching" Throbber showing after refresh when using [report_update_url="[bmlt_tabs report_update_url=""] shortcode

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/crouton#497]
Ameded the shortcode on searchable map 

[crouton_map map_search_auto="true", report_update_url="https://www.na.org.au/multi/regionalmeetingslistadmin/"]

To reproduce to to 
https://www.na.org.au/multi/searchable-map/

Throbber shows "Fetching..." as below

![image](https://github.com/user-attachments/assets/cad6a9e4-0a62-4b5d-8f3d-a9ca2d62aeb7)

**Expected behavior**
The "Fetching..." display should disappear after page has refreshed.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 129.0.6668.60

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS:  iOS 18
 - Browser both Chrome and safari
 - Version latest vesions

**Comment by otrok7** [comment]
I can't reproduce this.  Is it still an issue?

**Comment by brustar64** [comment]
Yes its still an issue.

Easy to generate if you put in a text search for a city.
The "Fetching" throbber remains on the page.

[cid:814c388b-ba95-4ce4-b6fd-d5fc66134f69]
________________________________

**Comment by otrok7** [comment]
Should be fixed in 3.20.7

**Comment by brustar64** [comment]
Its fixed!
Thanks so much for you service!
________________________________
