### ISSUE TITLE
some short codes are stuck on "fetching"

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/crouton#498]
**Describe the bug**
These short codes are stuck on "fetching" rather than showing the result:
`[service_body_names]`, `[meeting_count]`, and `[group_count]`

This started in 3.20.1; they were ok in 3.20.0

**To Reproduce**
1. Go to https://meetings.wszf.org
2. See error for service body names, meeting count, and group count.

**Expected behavior**
The display should show the service body names, meeting count, and group count.

**Comment by alanb2718** [comment]
I rolled back the crouton version used for https://meetings.wszf.org/ since people rely on it.  There is a copy of the website that uses the latest version and that shows the bug at https://staging32.meetings.wszf.org

**Comment by alanb2718** [comment]
Sorry to be the bearer of annoying news .... #499 fixes the `[meeting_count]` and `[group_count]` shortcodes, but now there is a bug in `[service_body_names]`: this now lists not just the current service body, but also its parent, grandparent, etc.  See https://staging32.meetings.wszf.org/ -- this should be showing only Lower Columbia Area, but the display also includes the region and zone.

**Comment by otrok7** [comment]
Closed in 3.20.5
