### ISSUE TITLE
service_body parameter stopped working

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/crouton#504]
The service_body parameter. has stopped working correctly in version 3.20.5.  Here are some examples.  These all work correctly in 3.20.4

This says there are no meetings (but there are):
`[bmlt_tabs service_body='199,373' root_server='https://aggregator.bmltenabled.org/main_server' ]`

This only shows meetings for service body 5:
`[bmlt_tabs service_body='3,5' root_server='https://bmlt.wszf.org/main_server' ]`

This only shows meetings for service body 3:
`[bmlt_tabs service_body='5,3' root_server='https://bmlt.wszf.org/main_server' ]`

**Comment by otrok7** [comment]
Closed in 3.20.6
