### ISSUE TITLE
Search by location in shortcode and querystring not working anymore

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/crouton#510]
**Describe the bug**
It used to be that you could pass via shortcode (or querystring) a location.  Crouton would geocode that and then make a lat/lon search to the root server.  

For example you could do http://example.org/crouton?map_search[location]=Matawan,NJ

Or

[bmlt_tabs map_search_location="Matawan,NJ"]

It appears that this functionality is lost, but I could be wrong.  This worked on crouton 3.15.3, not sure when it actually stopped working.

**Comment by otrok7** [comment]
The query string parameter matches the shortcode attribute, that is, it expects `?map_search_location` not `map_seach[location]`.  WouldN't be a problem to add this back in, it's just that it's a special case, and makes the code a bit ugly (er).  The close bracket is a problem in the attribute, the user has to escape them or translate them.  So I think it's much easier and cleaner if we say query string parameters match shortcode attributes, and the short code attribute does not contain brackets.  But if this breaks existing code or you think it's important, I will add it back in.  Your call.

**Comment by dgershman** [comment]
It was less about the parameter name and more about the functionality.  I'll have to try it out and see if works

**Comment by dgershman** [comment]
Ok this is good, closing.
