### ISSUE TITLE
Refactor Dropdowns and Tabs

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/crouton#53]
After Crouton 2.0.0 was released, all the table data was moved to the client side.  We introduced client-side templating using Handlebars.js.  This has made the code very maintainable.  

The code could benefit from an additional refactor of moving the rendering of the toolbar (dropdowns, buttons, and tabs) to also be rendered on the client side.

This would be a nice weekend project for someone who wants to get their feet wet.

**Comment by pjaudiomv** [comment]
quick edit, Crouton 2.0.0 not Yap 2.0.0
