### ISSUE TITLE
Make crouton more mobile friendly

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#59]
When on mobile devices crouton currently just goes to a day list, it would be nice to make the plugin more mobile friendly and responsive so you could see some of the tabs and or drop downs.

**Comment by radius314** [comment]
in master

**Comment by pjaudiomv** [comment]
one of the easier ways this could be done is having an option to continue to display the header (weekday/city and dropdowns) if device is mobile. currently they get chopped off.

so this is what displays now
![Screen Shot 2019-03-10 at 8 55 23 PM](https://user-images.githubusercontent.com/34245618/54094393-ecd38d80-4376-11e9-9a5b-bf86e7dcb09c.png)


but we could show this

![Screen Shot 2019-03-10 at 8 55 33 PM](https://user-images.githubusercontent.com/34245618/54094401-f957e600-4376-11e9-8d21-3f7b28c89d7b.png)

someone could tweak and force this with css, but may be nice to make it the default display, or an option.

**Comment by pjaudiomv** [comment]
this would be helpful with larger data sets on mobile devices

**Comment by radius314** [comment]
Seems easy enough

**Comment by pjaudiomv** [comment]
https://github.com/bmlt-enabled/crouton/blob/ee5fd48e531283296c5f2e533d61172fc9244ddc/css/bmlt_tabs.css#L329-L332

I think changing this to `display: block` would do it

**Comment by radius314** [comment]
implemented in #97

**Comment by radius314** [comment]
fixed in 2.5.0
