### ISSUE TITLE
crouton doesn't display on ie11

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#72]
I get the following errors on ie11 and crouton doesn't display, I realize that probably less than 5% of people use ie11 so this may not be that big of a deal but if there was an easy fix we should probably do it.

SCRIPT1004: Expected ';'
meetings (328,17)
SCRIPT1004: Expected ';'
bmlt_tabs.js (314,15)
SCRIPT5009: 'getMeetings' is undefined
meetings (242,4)

**Comment by pjaudiomv** [comment]
this may not be possible as ie11 doesnt support es6 and is also kind of enabling people to not upgrade idk

**Comment by pjaudiomv** [comment]
probably more enabling, to try to waste time with this issue

**Comment by radius314** [comment]
i actually think this is worth fixing.  i view user experiences of the addict as being more important than the administrative side of the house.

**Comment by pjaudiomv** [comment]
found out one of the issues. IE doesn't support the for..of statement
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

and is used twice in bmlt_tabs.js

https://github.com/bmlt-enabled/crouton/blob/0c010ffc97789ed1f9c583b9ab958cdd1834053f/js/bmlt_tabs.js#L314

https://github.com/bmlt-enabled/crouton/blob/0c010ffc97789ed1f9c583b9ab958cdd1834053f/js/bmlt_tabs.js#L334

**Comment by pjaudiomv** [comment]
fix is in master and will be in next release.
