### ISSUE TITLE
Distance to meeting

### ISSUE THREAD

**Issue by sfrna** [bmlt-enabled/crouton#79]
Instruction to do this says "User has to have geolocation permissions turned on."

Turned on where?

**Comment by californiasteve** [comment]
In Google maps API

**Comment by pjaudiomv** [comment]
this has nothing to do with the google maps api. this is for the users device whether its mobile or computer. more info on this is here https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

usually if a website trys to get your location you get a pop up saying something like "This website is trying to access your location, do you want to allow? yes or no" if you click yes crouton will display distances, if you click no it will not

**Comment by pjaudiomv** [comment]
an example of this in use is here https://sca.charlestonna.org/sfrna/
