### ISSUE TITLE
Crouton Meeting Time Display Issue

### ISSUE THREAD

**Issue by otwna** [bmlt-enabled/crouton#86]
Crouton on WordPress 5.0.3, PHP 7.3 meeting time displays in odd format.  

![capture](https://user-images.githubusercontent.com/47168713/51959640-92a7ea00-2412-11e9-84ec-2e6dab9d1bc8.JPG)

**Comment by radius314** [comment]
Couldn't reproduce this on the same versions.  What's your short code?

**Comment by otwna** [comment]
Hey Danny,

I am using [bmlt tabs] and I also tried the show map shortcode. Same issue
with both. I just tried it again this morning. I also get a big black space
which seems to be for the map even when I use [bmlt tabs]

Thanks for looking into this,

Zach

**Comment by otwna** [comment]
Thank you

**Comment by radius314** [comment]
Re: this issue, is it live somewhere to view?  Or did you rollback to an older version?

**Comment by otwna** [comment]
I rolled back to Jack's plugin but hang on I'll reactivate crouton and send
you a link

**Comment by otwna** [comment]
The update fixed the blank space issue. Thanks, here's the link
https://www.otwna.org/meetings/

**Comment by radius314** [comment]
Thanks, looking at this now.

**Comment by radius314** [comment]
Ok I know what the issue is, working on a patch.

**Comment by otwna** [comment]
Thanks!

**Comment by radius314** [comment]
crouton 2.4.2 has been released and fixes this issue.

**Comment by otwna** [comment]
Thanks. I could remove the group count but I will roll back for now.
