### ISSUE TITLE
Some part of this project need to be translated

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#88]
Happy to get a replacement from BMLT-Tabbed-UI, but code has changed since so I will need a way how can translate, not the backend but some word from a front page.

Thank you Danny

![capture](https://user-images.githubusercontent.com/3509271/52152846-ef3f1b00-2645-11e9-8f59-6358b631ee84.PNG)

**Comment by radius314** [comment]
@Klodd65 there is a beta version available for you to test.  
https://github.com/bmlt-enabled/crouton/releases/download/2.5.0-beta1/crouton.zip

You can set the language by doing the following `[bmlt_tabs language="fr-CA"]`, for example.

There are a couple of words that need translating, which you can see here.  https://github.com/bmlt-enabled/crouton/blob/master/lang/fr-CA.php, you can send them over on this ticket.
