### ISSUE TITLE
Updated Crouton with Map

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/crouton#89]
I put the new crouton with the map on this page: https://etror.org/meeting-schedule-printable/
the map shows up on the website, but not on my iphone.
Danny suggested I post it here.

**Comment by pjaudiomv** [comment]
whats the short code you are using

**Comment by lucy12187** [comment]
I’ll forward you the error they were getting today on the tabbed plugin. I
wasn’t getting it but thought updating to crouton would help. Still haven’t
heard back from those guys if they were still getting that error.
No idea if that error has anything to do with why the map doesn’t work on
my iPhone.

If they respond they’re still getting an error on the website I’ll let you
know.

**Comment by radius314** [comment]
Using an iOS simulator and safari web developer tools I can see the bmlt_map div isn’t being rendered.

**Comment by radius314** [comment]
Closing, if it re-surfaces please open a new ticket.

**Comment by radius314** [comment]
The autosave issue will be fixed in 2.5.0 ref: #95
