### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#90]
Every thing looks OK for now. Some new feature need to be translated. 
Map --> Carte
Miles --> Km  ( international gmap code, not US ) or Km/Miles is equal to 8/5 (example: 8 km = 5 miles)
https://csrqna.membres.naquebec.org/trouver-une-reunion/

**Comment by californiasteve** [comment]
I may be needing to translate this into Italian soon also.

**Comment by radius314** [comment]
ready for testing 

https://archives.bmlt.app/crouton/crouton-build67-deda54f69022677f0af7f768200aac8b33991b47.zip

**Comment by californiasteve** [comment]
Tested it on my server and works as expected.
