### ISSUE TITLE
Area tab

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#92]
Some of areas are great but others included some meetings out of the  tab-displayed area .

**Comment by radius314** [comment]
Can you provide specific details?  Which areas are vs aren't?

**Comment by Klodd65** [comment]
Shortcode is [bmlt_tabs time_format="HH:mm" bmlt_tabs language="fr-CA" bmlt_tabs show_map="1" bmlt_tabs show_distance="1" bmlt_tabs has_areas='1'  has_sub_province='1' has_zip_codes='0' ] and this the beta 2.5.0

**Comment by radius314** [comment]
Which areas aren't great?

**Comment by Klodd65** [comment]
On tab of Abitibi-Témiscamingue [CSLAT] ID:4 is mixed with Région Anglophone [EANA] ID:14;
On tab of Beauce Appalaches [CSLBA] ID:5 is mixed with Groupes éloignés (Outreach) ID:15;
Tab of Centre-du-Québec [CSLCQ] ID 22 is OK;
Tab of Centre Mauricie [CSLCM] ID:6 is mixed with Rive-Nord [CSLRN] ID:16
Tab of Estrie [CSLE] ID:9 is mixed with Sud-Ouest de Montréal [CSLSO] ID:19;
Tab of Groupes éloignés ID: 15 is OK;
Montréal [CSLM] ID:10 is OK;
Ouest de île de Montréal [CSLOIM] ID:11;
Outaouais [CSLO] ID:12 is OK;
Pays d'en haut [CSLDPDH] ID:8 is with ID:18;
Québec [CSLQ] ID:13 is OK;
Rive-Nord [CSLRN] ID:16 is OK;
Rive-Sud [CSLRS] ID:21 is OK;
Trois-Rivières [CSLTR] ID:7 is OK;
Yamaska [CSLY] ID:20 is OK;

in resume, all areas ID X get mixed with ID 1X

**Comment by radius314** [comment]
I have been able to reproduce, thanks for the steps.

**Comment by radius314** [comment]
The fix for this is in 2.5.0-beta2 
https://github.com/bmlt-enabled/crouton/releases/download/2.5.0-beta2/crouton.zip

**Comment by radius314** [comment]
@Klodd65 have you tested this?

**Comment by radius314** [comment]
This was tested against the same data and it's resolved now.
