### ISSUE TITLE
Some of Sub-Province meeting list are not appear

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#93]
***States - not sub-province**** 
This for beta version 2.5.x, Abitbi-Témiscamingue, Centre-du-Québec, Chaudières-Appalaches, Côte-Nord, Gaspésie - Îles-de-la-Madeleine, Lanaudières, Montréal and Montérégie.
https://naquebec.org/trouver-une-reunion/

**Comment by radius314** [comment]
2.5.0-beta2 correct?

**Comment by Klodd65** [comment]
no

**Comment by radius314** [comment]
Which version is this happening on?

**Comment by Klodd65** [comment]
2.5.0-beta1 and 2, do i need to try the main version?

**Comment by radius314** [comment]
ok so both versions, thanks

**Comment by radius314** [comment]
main version not released yet

**Comment by Klodd65** [comment]
We can merge that bug with issue #94

**Comment by radius314** [comment]
These are counties, not states

**Comment by radius314** [comment]
sub province

**Comment by radius314** [comment]
This appears to be fixed.
