### ISSUE TITLE
Selected tab do not display (blank) any info if one or more words with special chars letters are requested. 

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/crouton#94]
Example: if I select tab by town, meetings or location as "Montréal, l'Étape or with apostrophe ('), it does'nt display any requested infos. It looks like encoding. Stable tag: 2.5.0 beta-2

**Comment by radius314** [comment]
Able to repro

**Comment by radius314** [comment]
will be fixed in 2.5.0
