### ISSUE TITLE
regression from 2.4.1 to 2.4.2

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#95]
when using `[bmlt_tabs has_tabs="0" header="0"]` the meetings are not viewing properly. this worked fine in 2.4.1 but broke in 2.4.2. the issue can be traced to the addition of this code.
https://github.com/bmlt-enabled/crouton/blob/ee5fd48e531283296c5f2e533d61172fc9244ddc/js/bmlt_tabs.js#L79-L81
if i remove that it displays fine.

before 2.4.2 this is how meetings displayed
![Screen Shot 2019-03-10 at 9 32 57 PM](https://user-images.githubusercontent.com/34245618/54095369-59ea2180-437d-11e9-8ad1-9d1466202157.png)

and with 2.4.2 I get this
![Screen Shot 2019-03-10 at 9 32 10 PM](https://user-images.githubusercontent.com/34245618/54095373-62425c80-437d-11e9-82ba-c858d0d7fbeb.png)

**Comment by pjaudiomv** [comment]
only the current days meeting displays and nothing else.

**Comment by radius314** [comment]
by nothing else, I can only understand from this ticket that one is grouping by and the other is not.

**Comment by radius314** [comment]
will be patched 2.5.0

**Comment by pjaudiomv** [comment]
cool that fixed it!
