### ISSUE TITLE
exclude zip codes not working with multiple zip codes

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#99]
when using exclude zip code option, one zip code works fine. When trying to use multiple zips separated by comma I get the following js error.

![Screen Shot 2019-04-29 at 9 44 37 AM](https://user-images.githubusercontent.com/34245618/56901848-0b94fd00-6a67-11e9-8c73-c82e0b830fed.png)

**Comment by radius314** [comment]
I could not reproduce this issue.

**Comment by pjaudiomv** [comment]
just uploaded video on slack reproducing problem, on latest build

**Comment by radius314** [comment]
fix is in master

**Comment by pjaudiomv** [comment]
👍

**Comment by radius314** [comment]
does that mean passed testing?

**Comment by pjaudiomv** [comment]
Yes it passed
